### ISSUE TITLE
Dead link on 96boards/Hikey (Lemaker)

### ISSUE THREAD

**Issue by loicpoulain** [96boards/documentation#124]
At http://www.96boards.org/product/hikey/

bottom page link is broken:
Please visit the HiKey Hardware User Manual for more information

pointing to:
https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/AdditionalDocs/UserManual.md

instead of this one (I assume):
https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/AdditionalDocs/HardwareUserManual.md

Regards,
Loic

**Comment by Mani-Sadhasivam** [comment]
@loicpoulain Product page has been updated. Can we please close this issue?

**Comment by loicpoulain** [comment]
Sure, thanks
