### ISSUE TITLE
repo sync fault!

### ISSUE THREAD

**Issue by mipsan** [96boards/documentation#129]
during **repo sync**, following failure occurred !
I tried couple of times and got same errors.
reference: https://github.com/96boards/documentation/wiki/RPB-AOSP-DragonBoard410c-Build

```
remote: Counting objects: 28356, done
remote: Finding sources: 100% (936/936)
remote: Total 936 (delta 588), reused 936 (delta 588)
오브젝트를 받는 중: 100% (936/936), 1.27 MiB | 3.77 MiB/s, 완료.
델타를 알아내는 중: 100% (588/588), 로컬 오브젝트 202개 마침.
https://android.googlesource.com/platform/external/llvm URL에서
   809bc6fc398..fe560523d1e  lldb-master-dev     -> aosp/lldb-master-dev
   3cef9810b2a..922eae4d2ea  upstream-master     -> aosp/upstream-master
 * [새로운 태그]             android-cts-5.1_r23 -> android-cts-5.1_r23
 * [새로운 태그]             android-cts-6.0_r22 -> android-cts-6.0_r22
 * [새로운 태그]             android-cts-7.0_r13 -> android-cts-7.0_r13
 * [새로운 태그]             android-cts-7.1_r9  -> android-cts-7.1_r9

error: Exited sync due to fetch errors
```
This error is retured at " `repo sync -j8`" command.

Thanks,

**Comment by daniel-thompson** [comment]
Is this the entire repo sync output? Google translate does suggest any of the supplied text is an error message...

If you are getting errors it would be better to run "repo sync" without the "-j8" since it will reduce the amount of parallel activity (which it turn should make error messages more obvious). Can you re-run and share the full output.

**Comment by mipsan** [comment]
Thanks Daniel, 

I tried same job as you said, without '-j8' option.
But same error occurred at different time as follow;
```
 * [새로운 태그]               v4.3-rc6               -> v4.3-rc6
 * [새로운 태그]               v4.3-rc7               -> v4.3-rc7

error: Exited sync due to fetch errors
```
This log was cut only several lines at the end.

I would like to run self-built Android M on DB410c indeed, 
but any kind of instructions did not help me.

Any other advice?

**Comment by daniel-thompson** [comment]
Still, in part, I suggest trying to switch repo into English. You mentioned you are *not* seeing a clear error report and I wonder it there might be some problem with the i18n.

I know this because I *do* get a clear error report:

    Fetching projects:  99% (462/466)  fatal: remote error: access denied or repository not exported: /gitroot/android-x86/platform/external/libpciaccess
    error: Cannot fetch platform/external/libpciaccess
    
    error: Exited sync due to fetch errors

This turns out to be because sourceforge has altered their git hosting requiring changes to the repo manifest. I made the following changes to my .repo/local_manifests as was able to complete the pull:
[sf_fix.txt](https://github.com/96boards/documentation/files/1287686/sf_fix.txt)

**Comment by mipsan** [comment]
Thanks Daniel,
To build, I modified `.repo/local_manifests/linaro.xml` as your diff.
Build job was done with couple of further modifications and running build command several times.
Finally, I've got 7 img files,  that is, 
```
boot-db410c.img  
boot.img  
cache.img  
dt.img  
ramdisk.img  
system.img  
userdata.img.
```

While flash fusing these img files through fastboot, system.img and userdata.img return fastboot fail and fastboot crashes.. 

Should I redefine partition for this target??

**Comment by daniel-thompson** [comment]
What version of the bootloader do you have installed? I suspect this release would have been tested with: http://builds.96boards.org/releases/dragonboard410c/linaro/rescue/16.06/dragonboard410c_bootloader_emmc_android-50.zip

**Comment by mipsan** [comment]
![image](https://user-images.githubusercontent.com/3205851/30352287-231a0794-985a-11e7-8b7c-1293a37c8870.png)

After installation dragonboard410c_bootloader_emmc_android-50.zip, 
when I try to fuse userdata.img and system.img, fastboot crashed with this error message on terminal.

Then, I'm re-building whole source tree to try once more.

**Comment by daniel-thompson** [comment]
Any news here?

What does the file command say about the images.

For example:

    wychelm$ file system.img 
    system.img: Android sparse image, version: 1.0, Total of 314554 4096-byte output blocks in 2809 input chunks.
    wychelm$ file userdata.img 
    userdata.img: Android sparse image, version: 1.0, Total of 1310720 4096-byte output blocks in 203 input chunks.

**Comment by mipsan** [comment]
Thanks Daniel,

I attach the result;

```
youngwha@db410c$ file system.img
system.img: Linux rev 1.0 ext4 filesystem data, UUID=da594c53-9beb-f85c-85c5-cedf76546f7a, volume name "system" (extents) (large files)
youngwha@db410c$ file userdata.img
userdata.img: Linux rev 1.0 ext4 filesystem data, UUID=c25d03d9-ea27-3358-873e-b911bfaab62b, volume name "data" (extents) (large files)
```

**Comment by daniel-thompson** [comment]
Interesting that these are not sparse images. Having said that fastboot should handle raw images like this automatically. How old if the version of fastboot you are using?
