### ISSUE TITLE
Op-TEE Support for Poplar Board.

### ISSUE THREAD

**Issue by heeleyth** [96boards/documentation#135]
Hi 

Any plans to add Op-TEE support for Poplar board?
And if yes any idea of the expected time frame. 

Tom.

**Comment by daniel-thompson** [comment]
Is there any problem with the documentation here?

Sounds like this is better discussed on the forum: https://discuss.96boards.org/t/tee-os-on-poplar/2861

**Comment by heeleyth** [comment]
Thanks for the link. 

No problem with documentation my fault for using wrong forum.

My excuse very minor ref to op-tee on this https://github.com/96boards/documentation/issues/39 

Closing the comment

**Comment by daniel-thompson** [comment]
No worries. Regarding #39: to be honest in the past we've been a bit too liberal in the tickets we leave open against the docs.
