### ISSUE TITLE
pdf damaged

### ISSUE THREAD

**Issue by hipboi** [96boards/documentation#139]
`documentation/Addenda/96BoardsCESpecification-CameraModuleInterfaceAddendum.pdf`

This file is damaged, I can not preview online. Neither can open it after download file.

**Comment by sdrobertw** [comment]
Thank you @hipboi for pointing this out.

I will look into this and try to provide an update.

**Comment by sdrobertw** [comment]
This should be fixed now, @hipboi 

Please close the issue, if you are satisfied. Thanks!

**Comment by hipboi** [comment]
Thanks.
