### ISSUE TITLE
No autogen.sh file in libsoc package

### ISSUE THREAD

**Issue by nuodong** [96boards/documentation#14]
In documentation/ConsumerEdition/GPIO/Advanced/libsoc-install/README.md, Command section: 
There is a command specifying  $ ./autogen.sh<Enter> , but there is no such file in libsoc package.

**Comment by sdrobertw** [comment]
Did you try going through the instructions as is, without skipping the $ ./autogen.sh command?

**Comment by nuodong** [comment]
Yes, I go through the libsoc package and there is no such command.

**Comment by sdrobertw** [comment]
Before attempting to build the library, did you update your system and install all dependencies?

$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get dist-upgrade

$ sudo apt-get install git build-essential autoconf automake libtool swig3.0 python-dev nodejs-dev cmake pkg-config libpcre3-dev

$ sudo apt-get clean

**Comment by sdrobertw** [comment]
I have recreated this issue, I am working to resolve now. I should have something within the day.

Thank you!

**Comment by sdrobertw** [comment]
Please replace the $ ./autogen.sh command with the following:

$ autoreconf -i

everything else should be fine. I will confirm this tomorrow.

**Comment by sdrobertw** [comment]
Method using $ ./autogen.sh can be performed as follows. 

$ wget https://github.com/jackmitch/libsoc/archive/0.8.1.tar.gz
$ tar -zxvf 0.8.1.tar.gz
$ cd libsoc-0.8.1
$ ./autogen.sh
$ ./configure --enable-board=dragonboard410c --enable-python=3 |& tee py3_conf.log
$ make V=1 |& tee make.log
$ sudo make install
$ sudo ldconfig -v -N

I will adjust the documentation accordingly. Thank you very much for your contribution! Please let me know if this works so I can resolve the issue.

**Comment by sdrobertw** [comment]
@nuodong 

Can we close this issue?

**Comment by sdrobertw** [comment]
I will close this issue, please open a new issue if you continue to experience problems while
building this library.

Thanks
