### ISSUE TITLE
URL Changes 

### ISSUE THREAD

**Issue by kylekirkby** [96boards/documentation#148]
There has been a recent permalink change that has subsequently broken the build as many other pages are using the old permalink still. In the future can we make sure that any permalink changes are submitted as a Pull Request and approved by either @shovanuk or myself so we can double check it before merging?

Many Thanks,

Kyle

**Comment by sdrobertw** [comment]
@kylekirkby @shovanuk 

Yes, good observation.

Any permalink changes will have you tagged to make sure nothing breaks.
