### ISSUE TITLE
Android SD card image download points to wrong image

### ISSUE THREAD

**Issue by molecule** [96boards/documentation#15]
The Download link for the latest Android
http://www.96boards.org/db410c-getting-started/Downloads/Android.md/

is still pointing to 16.03:
builds.96boards.org/releases/dragonboard410c/qualcomm/android/16.03/dragonboard410c_sdcard_install_android-*.zip
 
instead of 16.06:
http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/

 "Latest" points correctly to 16.06:
http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/latest/

**Fix**:
Update the "Download" link here: 
https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/Downloads/Android.md#sd-card-image

To point to the correct "latest" link rather than having the hard-coded value 16.03:
http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/latest/

**Comment by sdrobertw** [comment]
Due to bugs found in the 16.06 Android release, I have reverted the links back to 16.03. I will add a disclaimer to the page to inform of this issue.

Once these bugs are addressed, links will return to "latest" so they can once again remain dynamic.

**Comment by molecule** [comment]
Sounds good! Thanks for the clarification. I assume you're referring to this issue:
http://www.96boards.org/forums/topic/unfortunately-the-process-com-android-phone-has-stopped-dragonboard/

16.03 is build #99, and 16.06 is build #118. Is there any possibility of getting access to any of the builds between 99 and 118? Maybe... build 117?

**Comment by sdrobertw** [comment]
@molecule 

Yes, the issue you pointed out in the forum is correct. This was pointed out to me at the AT&T Shape event by some of the hackers, as well as by some other folks inside Qualcomm. While it is being addressed we recommend stepping back to the last stable release which is 16.03:
http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/16.03/

96Boards DragonBoard 410c Downloads page mirrored download links have also been stepped back to 16.03 and can be found here: 
https://www.96boards.org/db410c-getting-started/Downloads/Android.md/

---

If you would like to try some of the builds between #99 and #118, you can visit the snapshots folder here:
http://builds.96boards.org/snapshots/dragonboard410c/qualcomm/android/

**Comment by molecule** [comment]
Great! Thanks for the link to the snapshots folder. Looks like they're all pretty funky in there. Many of them won't even boot. We'll just have to wait for a new working release...hopefully soon!
