### ISSUE TITLE
Broken link on B2260 Debian Documentation Page

### ISSUE THREAD

**Issue by kylekirkby** [96boards/documentation#150]
https://github.com/96boards/documentation/tree/master/ConsumerEdition/B2260/Downloads/Debian.md is linking to http://builds.96boards.org/snapshots/b2260/linaro/debian/latest/b2260-jessie_alip_*.img.gz and http://builds.96boards.org/snapshots/b2260/linaro/debian/latest/b2260-jessie_developer_*.img.gz which no longer exists. Are there suitable replacements available for these?

Many Thanks,

Kyle

**Comment by daniel-thompson** [comment]
This is similar to issues on other 96Boards. If the teams that wrote the software move to other things without issuing an official release then the links in the docs break when the reaper cleans out the old snapshots.

We can solve this either by making the reaper less aggressive or reducing the barriers to making official releases (so we never need to link to snapshots in the documentation). I actually favour the later... for users the difference between a release and a snapshot if not very visible when the docs link to snapshots.

**Comment by kylekirkby** [comment]
Hi all, the above links were fixed by replacing jessie with stretch. There have been a couple more broken links found relating to OS images on builds.96boards.org. The following are returning a 404.


29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/
-- | --
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/rpb-console-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/rpb-weston-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/rpb-console-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/rpb-desktop-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/rpb-console-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/rpb-weston-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/rpb-console-image-stih410-b2260-*.stimg
29-Oct-2017 19:49:17 | ./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/rpb-desktop-image-stih410-b2260-*.stimg


If anyone knows what the replacements for these broken links should be please let me know so we can update them.

Many Thanks,

Kyle

**Comment by sdrobertw** [comment]
@kylekirkby I am guessing this has been fixed since we have not seen any broken links in the build logs lately around the B2260. I am going to close this issue.
