### ISSUE TITLE
Breadcrumb on website seems to be one directory off

### ISSUE THREAD

**Issue by jonberling** [96boards/documentation#16]
I was browsing http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/15.06/

The breadcrumb path at the top of the page seems to be off by one. If I want to navigate back to http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/, I need to click on the qualcomm link. Likewise if I want to navigate to http://builds.96boards.org/releases/dragonboard410c/qualcomm/, I need to click on the dragonboard410c link.

This us using Chrome (not chromium) on Ubuntu 14.04.

**Comment by sdrobertw** [comment]
Thank you @jonberling 

I have tried to replicate this issue on the following host machines/operating systems:

Ubuntu 15.04 - Firefox: cannot replicate issue
Windows 10 - Chrome: cannot replicate issue
MacOSX Mavericks - Safari and Chrome: cannot replicate issue

Clicking forward by choosing a directory option, or going back by clicking the "Parent Directory" link should work. 

Is the "Parent Directory" link not present on your system?

**Comment by molecule** [comment]
I just recreated this on Firefox on Windows:
1. Start in 15.06: http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/15.06/
2. Want to see the list of all android builds, not just 15.06, so I click on "android" on the top: http://imgur.com/a/Czfu5
3. Nothing happens, I stay on the same 15.06 page.
4. Click on "qualcomm" (to the left of "android" in the picture above), and now I go to the android subdirectory: http://builds.96boards.org/releases/dragonboard410c/qualcomm/android/
5. If I click on "android" now (same as in step 2), the URL looks like this (note the two slashes at the end): http://builds.96boards.org/releases/dragonboard410c/qualcomm/android//

Parent Directory works, it's just broken if you try to navigate directly via the path links.

**Comment by sdrobertw** [comment]
Okay, it looks like I was not understanding the issue. I have replicated it on all of my previously mentions host machines/operating systems listed in a previous comment:

Ubuntu 15.04 - Firefox: issue has been replicated
Windows 10 - Chrome: issue has been replicated
MacOSX Mavericks - Safari and Chrome: issue has been replicated

I will look further into this.

**Comment by ShovanSargunam** [comment]
@doanac can you look at this? 

Thanks

**Comment by sdrobertw** [comment]
@fboudra maybe?

**Comment by fboudra** [comment]
it's Systems team territory, hence for @doanac

**Comment by sdrobertw** [comment]
@doanac any news on this one?
