### ISSUE TITLE
Installation instructions should link to Downloads page.

### ISSUE THREAD

**Issue by molecule** [96boards/documentation#17]
This documentation doesn't have a link back to the Downloads page (I assume it's the same for the other Download instructions too):

Step 2: Recall Download Location
    Locate SD card install file from Downloads page.
    This file will be needed for the next step.

The phrase "Downloads page" should link to the Downloads page:
http://www.96boards.org/db410c-getting-started/Downloads/README.md/

**Comment by sdrobertw** [comment]
Thank you @molecule 

This has been addressed in the github, self rendering should take place on the website by end of day.

Please see commits below:

https://github.com/96boards/documentation/commit/b7df2ed7d6bb112eaf6833b2691d51fdc73ba078
https://github.com/96boards/documentation/commit/bda776d3a43e70c44a445554ac2b08df25c609e7
https://github.com/96boards/documentation/commit/f7839bc1998ea2bdb0c4d03d608bf0804f6525e0

**Comment by molecule** [comment]
Thanks!
