### ISSUE TITLE
Comments on Documentation

### ISSUE THREAD

**Issue by shovanuk** [96boards/documentation#172]
Hay, 

I am thinking of adding a comment section to documentation pages [1] (Like how we have on Blog[2]). This will encourage the community to discuss on particular docs and help us improve them. 

What do you say?

[1] https://www.96boards.org/documentation/IoTEdition/carbon/getting-started/
[2] https://www.96boards.org/blog/basic-threads-zephyr/

Thanks
Shovan

**Comment by daniel-thompson** [comment]
On 30/10/17 09:42, Shovan wrote:
> Hay,
> 
> I am thinking of adding a comment section to documentation pages [1] 
> (Like how we have on Blog[2]). This will encourage the community to 
> discuss on particular docs and help us improve them.
> 
> What do you say?

I'd rather enrich the "Edit on github" bits by adding automatic "Report 
an problem with this page" that also link properly into github:

https://github.com/96boards/documentation/issues/new?title=Problem%20with%20ConsumerEdition/HiKey/README.md&body=Let%27s%20write%20some%20text%20to%20ensure%20we%20get%20bug%20reports,%20not%20things%20that%20should%20be%20discussed%20on%20the%20forum


Daniel.

**Comment by shovanuk** [comment]
@daniel-thompson nice one, we can add the feature in

**Comment by sdrobertw** [comment]
This has been resolved as can be seen on all 96Boards.org github rendered pages.

Closing...
