### ISSUE TITLE
Problem with ConsumerEdition/HiKey960/Downloads/README.md

### ISSUE THREAD

**Issue by vishalashapur** [96boards/documentation#185]
Hi, I built aosp from source for hikey960. now i want to flash those images and i know how to flash. but my doubt is already hikey 960 board has builtin image of aosp. if i flash my new images will they work correctly or what happens to old image?

**Comment by daniel-thompson** [comment]
This kind of question really is better asked on the forum: https://discuss.96boards.org/ . While some questions do arise from inadequate documentation I'm not sure that this the case here, as far as I am aware the instructions on how to flash do work correctly (e.g. they overwrite the previous image).
