### ISSUE TITLE
Add OpenEmbedded to ConsumerEdition/HiKey960/Downloads/README.md

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#189]
On the forum users are being pointed at OE/RPB binary snapshots. I know these are only snapshots (OpenEmbedded being primarily build-from-source) but without any documentation its what people tend to get pointed at.

Personally I think pointing users at the binary snapshots is a mistake; the images are useful for testing but it tends to lead them to have extremely incorrect expectations of what they can do with the resulting install but nevertheless it would be good to bring Hikey960 within the scope of the OpenEmbedded guide and, perhaps, link out to it from this page.

c.f. https://discuss.96boards.org/t/how-soon-until-a-linux-prebuilt-image-is-available/1715/39

**Comment by daniel-thompson** [comment]
> ... and, perhaps, link out to it from this page.

"this" meaning the page in the title of the bug report (nothing to do with the c.f. at the bottom)

**Comment by Mani-Sadhasivam** [comment]
@daniel-thompson I will work on it. Thanks!

**Comment by Mani-Sadhasivam** [comment]
Since no one from HiSilicon landing team is willing to sign off the release image, there is no chance for getting that. So even though it is not recommended, we should be using snapshot images for now :(

**Comment by daniel-thompson** [comment]
Huh? The issue is that OpenEmbedded is not documented on https://www.96boards.org/documentation/consumer/hikey960/downloads/ .

The user feedback that I was passing on is:
> A clear documentation that has been VERIFIED and VALIDATED is needed.
> There is no central location of detailed steps on how a linux distribution has
> been used on the 960 with the blinking lights and hdmi support. This
> document should support linux installation WITH and WITHOUT UART.
>
> The community needs this, not everyone is trying to do android development.

**Comment by Mani-Sadhasivam** [comment]
@daniel-thompson Ahh. Sorry, I overlooked the OE part. Added the OE guide for HiKey960 to my TODO list.

Thanks

**Comment by daniel-thompson** [comment]
On Mon, Jun 04, 2018 at 02:09:16AM -0700, Manivannan Sadhasivam wrote:
> @daniel-thompson Ahh. Sorry, I overlooked the OE part. Added the OE guide for HiKey960 to my TODO list.

No worries.

FWIW I also think the way we manage snapshots -> release is rather
dysfunctional. However I don't view HiSi LT as the problem. More
that the assumption that they must bless is broken. We see exactly
the same problem on other boards, such as Bubblegum96, so the problem
is more likely in the assumption that a team that didn't really work on
the build needs to bless it.

Essentially we are combining a very lightweight snapshot process (that
allows lots of useful experimental builds to be produced) with a very
heavyweight release process that makes releasing any successful
experimental build impossible.

**Comment by photoszzt** [comment]
I find an OE documentation here: https://github.com/96boards-hikey/Documentation/blob/master/hikey960-openembedded-linux-mainline.md Not sure whether anyone has tried that.

**Comment by Mani-Sadhasivam** [comment]
@photoszzt Thanks for the link!

That documentation is for using the OE build generated by Linaro and not for building the OE RFS from scratch. I'm working on adding a HiKey960 OE build doc. Please stay tuned :)

**Comment by photoszzt** [comment]
@Mani-Sadhasivam  I saw the oe guide still uses morty but I saw linaro already releases rocko builds. Can I use the rocko branch rather than the morty? Plus, sumo is also stable now. Is there any plan to support sumo?

**Comment by Mani-Sadhasivam** [comment]
@photoszzt Good point! We are just following the upstream Linaro OE guide which still uses `morty`. By anyway there is no reason to use the old version. @ndechesne @daniel-thompson  Can we switch to `rocko` or `sumo` in 96Boards OE guide?

**Comment by ndechesne** [comment]
You could , and should, switch to sumo branch.

**Comment by Mani-Sadhasivam** [comment]
@ndechesne Thanks for the confirmation. Will submit a PR for that.
