### ISSUE TITLE
Problem with ConsumerEdition/DragonBoard-410c/Guides/USBWebcam.md

### ISSUE THREAD

**Issue by ravilape** [96boards/documentation#201]
Please enter some details about the bug/issue so we can promptly resolve it.

**Comment by shovanuk** [comment]
Thanks for reporting @ravilape 

@Mani-Sadhasivam @ric96 looks like the page is empty?
https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Guides/USBWebcam.md.html

Thanks
Shovan

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam @ric96 
Could you please address this issue?

Thanks.

**Comment by Mani-Sadhasivam** [comment]
@ric96 Can you please modify the link to the new location or just remove it?
