### ISSUE TITLE
Problem with ConsumerEdition/B2260/Downloads/OpenEmbedded.md

### ISSUE THREAD

**Issue by kylekirkby** [96boards/documentation#204]
Hi Guys,

The link checker has found some more broken links on this page.

https://www.96boards.org/documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html

build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/rpb-weston-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/rpb-desktop-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/rpb-weston-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/rpb-desktop-image-stih410-b2260-

Many Thanks,

Kyle

**Comment by sdrobertw** [comment]
Closed issue because this was addressed with the following Pull Request:
https://github.com/96boards/documentation/pull/219
