### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by kylekirkby** [96boards/documentation#205]
Hi Guys the latest broken links from the 96boards build are listed below:

build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/gpio/README.md.html, ./documentation/ConsumerEdition/guides/mraa/gpio/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/i2c/README.md.html, ./documentation/ConsumerEdition/guides/mraa/i2c/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/index.html, ./documentation/ConsumerEdition/guides/mraa/gpio/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/index.html, ./documentation/ConsumerEdition/guides/mraa/i2c/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/index.html, ./documentation/ConsumerEdition/guides/mraa/led/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/index.html, ./documentation/ConsumerEdition/guides/mraa/uart/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/led/README.md.html, ./documentation/ConsumerEdition/guides/mraa/led/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/mraa/uart/README.md.html, ./documentation/ConsumerEdition/guides/mraa/uart/index.html
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/guides/open_embedded.md.html, https://developer.qualcomm.com/download/linux-ubuntu-board-support-package-v1.1.zip
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/imx7-96/getting-started/index.html, https://github.com/sdrobertw/meercat/blob/master/guides/files/iMX7-96-software-guide.pdf
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/imx7-96/getting-started/index.html, https://github.com/sdrobertw/meercat/blob/master/hardware-docs/files/iMX7-user-guide.pdf
build	30-Nov-2017 06:57:37	./documentation/IoTEdition/guides/compare_96boards_ie.md.html, ./documentation/IoTEdition/guides/index.html

build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb-wayland/latest/rpb-weston-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/jethro/stih410-b2260/rpb/latest/rpb-desktop-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb-wayland/latest/rpb-weston-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/rpb-console-image-stih410-b2260-*.stimg
build	30-Nov-2017 06:57:37	./documentation/ConsumerEdition/B2260/Downloads/OpenEmbedded.md.html, http://builds.96boards.org/snapshots/reference-platform/openembedded/krogoth/stih410-b2260/rpb/latest/rpb-desktop-image-stih410-b2260-*.stimg

**Comment by sdrobertw** [comment]
I will look into this. I know I will be fixing many of the broken links under the DB410c/VendorDocs.

Any help from @Mani-Sadhasivam and @ric96 is appreciated.

**Comment by Mani-Sadhasivam** [comment]
Submitted #210

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam @kylekirkby Has this issue been resolved?

If so, please close. Thanks!

**Comment by Mani-Sadhasivam** [comment]
I have submitted my fix and yesterday @kylekirkby also submitted a PR for fixing broken links. Kyle can you please confirm and close this issue?

**Comment by Mani-Sadhasivam** [comment]
@kylekirkby Are we good to close this issue?
