### ISSUE TITLE
SD card flash on Debian

### ISSUE THREAD

**Issue by Githubforum** [96boards/documentation#208]
I am trying to flash from SD card, but always get "no space left on device" during SD card flashing ,eventhough i am using 32GB micro sd card. I followed the document provided in github, but no luck. Help please...

**Comment by sdrobertw** [comment]
@Githubforum Could you please specify a link to the exact instruction set you are following?

**Comment by sdrobertw** [comment]
@Githubforum 

Other statements that might help us troubleshoot for you:

- Your host machine and OS (Mac, PC... Windows, OSX, Ubuntu etc....)
- Speed class of sd card (https://en.wikipedia.org/wiki/Secure_Digital) this link might help
- Are you formatting the SD card prior to flashing? 
- If you are flashing sd card using command line and dd command, could you please share the command you are using?

**Comment by Githubforum** [comment]
Thanks for the response.

This is the link for installation guide for SD card boot. 
https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/Installation/LinuxSD.md
I am using Sandisk 32GB micro SD card. The link mentioned has the commands I used for. 
I am formatting SD card prior to flashing(On windows machine).
host machine is running Ubuntu 14.04 LTS, which I am using to flash SD card.
DD command I used is
 sudo dd if=dragonboard410c_sdcard_developer_debian-283.img of=/dev/7021-BAED  bs=4M oflag=sync status=noxfer

where " dragonboard410c_sdcard_developer_debian-283.img" is the one which I got it from the link I mentioned at top. "7021-BAED" is my SD card name.

command to flash image. I am getting an error " no space left on device".

**Comment by ric96** [comment]
Hi, the name of the sdcard would be something like /dev/sdZX or /dev/mmcblkpX. The easiest way to check the name on Ububtu is to use the Disks application, it's already installed on ubuntu.
Or Run sudo fdisk -l in a terminal

**Comment by Githubforum** [comment]
Thanks for response.
I used lsblk command on terminal and the name of the SD card appears as

/media/username/7021-EABD. So I used 7021-EABD as SD card name. Do I need to provide full path of SD card or only the name?

**Comment by ric96** [comment]
For example
```shell
Device     Start        End    Sectors  Size Type
/dev/sdb1  65535 3906344744 3906279210  1.8T Linux filesystem
```
the Device Name is to be used and it will ALWAYS have /dev/ in the begining

**Comment by Githubforum** [comment]
I used command 
sudo dd if=dragonboard410c_sdcard_developer_debian-283.img of=/dev/7021-BAED bs=4M oflag=sync status=noxfer

It includes  /dev/ 7021-EABD as the SD card name. Is this correct?..

**Comment by ric96** [comment]
No, can you send me the output of ```sudo fdisk -l```

**Comment by Githubforum** [comment]
![error](https://user-images.githubusercontent.com/34318201/33685179-bbba65b2-da9e-11e7-9465-134eb327585a.png)
![snapshot](https://user-images.githubusercontent.com/34318201/33685181-be7f523a-da9e-11e7-9fc8-4a5e4bf6a0f2.png)
Attached pictures.

**Comment by ric96** [comment]
it should be ```of=/dev/sdb```

**Comment by Githubforum** [comment]
![dev_name](https://user-images.githubusercontent.com/34318201/33685354-4d01d1f4-da9f-11e7-9990-60269dd942ba.png)

**Comment by ric96** [comment]
it should be ```of=/dev/sdb```

**Comment by Githubforum** [comment]
So, I n need to use of=/dev/sdb/7021-EABD, its only of=/dev/sdb correct?

**Comment by ric96** [comment]
correct

**Comment by sdrobertw** [comment]
@Githubforum 

Every time you remove and insert your sd card be sure to recheck the name it is under. dd command can be very destructive if you are not careful.

Based on the most current print out you provided your disk name is "sdb", hence the command you will use to flash the sd card is:

"sudo dd if=dragonboard410c_sdcard_developer_debian-283.img of=/dev/sdb bs=4M"

If your problem is resolved, please close this issue.

Thanks! I hope this helped! :)

**Comment by Githubforum** [comment]
Thanks for info.. 
Now the image is placed onto SD card. Thanks guys..
