### ISSUE TITLE
Login credentials for linaro developer

### ISSUE THREAD

**Issue by Githubforum** [96boards/documentation#209]
With support , the imageg has been placed onto SD card. After inserting it into the dragon board, I get message

Debian GNU/Linux 9 Linaro-developer tty1
linaro-developer login:

In here I tried creating a login, with user name  and password. After I try creating a password, it says, incorrect password,

What this means?.. the password is already set in that?.. or I have to create one?..

**Comment by ric96** [comment]
try root/linaro or linaro/linaro

**Comment by Githubforum** [comment]
linaro/linaro worked . Thanks a lot.

**Comment by sdrobertw** [comment]
@Githubforum Are you on IRC by chance?

**Comment by Githubforum** [comment]
I did not get it.. IRC?..

**Comment by Githubforum** [comment]
Internet relay chat?..

**Comment by sdrobertw** [comment]
@Githubforum 

Yes, IRC = Internet Relay Chat

We are in channels #96Boards and #OpenHours

You should join these channels and hang out with us. Always there chatting live. A free way to access IRC is through freenode

http://webchat.freenode.net/

Just create whatever Username you like and then enter the #chatroom and looks for us.

Sahaj is ric96 and I am sdrobertw :D

**Comment by sdrobertw** [comment]
@Githubforum I would recommend joining #OpenHours channel first

**Comment by Githubforum** [comment]
sure

**Comment by Githubforum** [comment]
since now the SD card boot is ok, I am trying to run opengles_capture example code provided in 410c_board support link.
https://github.com/D3Engineering/410c_camera_support/wiki/OpenGLES-Capture-Example-User-Guide

How to copy this code from here and make it to run on 410c board?.

**Comment by sdrobertw** [comment]
@ric96 @Githubforum Is this issue resolved?

If so, please close.

I would also suggest taking this issue to the 96Boards forums. There you will get much more visibility from the community and our support team:

https://discuss.96boards.org/

Thanks!

**Comment by Mani-Sadhasivam** [comment]
since the original issue is resolved, closing this issue. @Githubforum please take your further questions on other topics to [96Boards Forum](https://discuss.96boards.org/)
