### ISSUE TITLE
Do i need to create a partition on SD card ,to execute an application on it?

### ISSUE THREAD

**Issue by Githubforum** [96boards/documentation#211]
I have Dragonboard410c , which I am booting from SD card. Now I want  to run an imager application on to it. The source code is in 
https://github.com/D3Engineering/410c_camera_support/wiki/OpenGLES-Capture-Example-User-Guide
how to copy this onto SD card and run on it?..

**Comment by sdrobertw** [comment]
@Githubforum 

@ric96 , would you mind sharing your guide with @Githubforum for sdcard image flashing? 

The only reservation I have is that the D3 image is a custom image, thought I feel it should still work.

Thanks.

**Comment by sdrobertw** [comment]
@Githubforum I would also suggest taking a question like this to the forums:

https://discuss.96boards.org/

There you will get much more visibility from the community and our support team.

**Comment by Mani-Sadhasivam** [comment]
@Githubforum You don't need to create a partition for executing the application. Just Clone and build the application from source as mentioned [here](https://github.com/D3Engineering/410c_camera_support/wiki/OpenGLES-Capture-Example-User-Guide#compilation)

**Comment by Mani-Sadhasivam** [comment]
For further questions, please open a thread in [96Boards Forum](https://discuss.96boards.org/)
