### ISSUE TITLE
compilation error "use option -std=c99,"

### ISSUE THREAD

**Issue by adhamnegmsourcya** [96boards/documentation#212]
whenever i attempt to build i receive the following error 

"external/libdrm/xf86drm.c: In function 'parse_separate_sysfs_files':
external/libdrm/xf86drm.c:3102:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for (unsigned i = ignore_revision ? 1 : 0; i < ARRAY_SIZE(attrs); i++) {
     ^
external/libdrm/xf86drm.c:3102:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
external/libdrm/xf86drm.c: At top level:
cc1: warning: unrecognized command line option "-Wno-enum-conversion"
make: *** [out/target/product/db410c/obj/STATIC_LIBRARIES/libdrm_intermediates/xf86drm.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.

#### make failed to build some targets (03:43 (mm:ss)) ####
"

i followed the steps here :https://github.com/96boards/documentation/wiki/RPB-AOSP-DragonBoard410c-Build

i faced an issue in pulling the source code i solved by following instructions here:https://github.com/96boards/documentation/issues/129

i tried adding "ccflags-y := -std=c99" and  "LOCAL_CFLAGS += -std=c99" to build/core/main.mk and external/libdrm/Android.mk with no success 

[out.txt](https://github.com/96boards/documentation/files/1547771/out.txt)

**Comment by sdrobertw** [comment]
@ric96 I believe this is your specialty, could you please address, label and close this issue when it has been resolved.

thanks!

**Comment by sdrobertw** [comment]
@adhamnegmsourcya 

I would also suggest taking this issue to the 96Boards forums. There you will get much more visibility from the community and our support team:

https://discuss.96boards.org/

Thanks!

**Comment by Mani-Sadhasivam** [comment]
Same issue has been reported in forum
https://discuss.96boards.org/t/aosp-compilation-error-use-option-std-c99/3626
