### ISSUE TITLE
Problem with ConsumerEdition/DragonBoard-410c/Guides/USBWebcam.md

### ISSUE THREAD

**Issue by tejaswisj** [96boards/documentation#213]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Guides/USBWebcam.md.html

**Comment by daniel-thompson** [comment]
This has moved to https://www.96boards.org/documentation/ConsumerEdition/guides/multi-usb-camera.md.html so we need to fix the link rather than this page. What link did you follow to get here?

**Comment by sdrobertw** [comment]
@tejaswisj @daniel-thompson 

Has this issue been addressed? If so, please close.

Thanks!

**Comment by Mani-Sadhasivam** [comment]
@tejaswisj Can you please let us know the page which referenced this link?

**Comment by daniel-thompson** [comment]
> @daniel-thompson: Has this issue been addressed? 

Me? Not a clue I'm afraid. The reporter has not replied to my question!

**Comment by Mani-Sadhasivam** [comment]
Closing as we didn't get any response from the reporter!
