### ISSUE TITLE
fastboot stuck on "waiting for devices"

### ISSUE THREAD

**Issue by atoaster** [96boards/documentation#22]
I am trying to install Android on the lemaker hikey 8gb MMc version (I think it's 8gb, how do you check?). I can succesfully flash the ptable using:`
sudo fastboot flash ptable ptable-aosp-8g.img`

then the light on the board comes on. I do sudo fastboot reboot, the light turns off, I check for the device with ls /dev/ttyUSB* and the output is:
/dev/ttyUSB0

But when I run the command:`
sudo fastbot flash fastboot fip.bin`
The terminal hangs on "waiting for device"

The jumpers are in the correct position still (auto boot and bootloader select), and the output of the python script was:
```
sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin
[sudo] password for gerald: 
+----------------------+
(' Serial: ', '/dev/ttyUSB0')
(' Image1: ', 'l-loader.bin')
(' Image2: ', '')
+----------------------+

('Sending', 'l-loader.bin', '...')
Done

```

The output of the ptable command was:
```
sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin
[sudo] password for gerald: 
+----------------------+
(' Serial: ', '/dev/ttyUSB0')
(' Image1: ', 'l-loader.bin')
(' Image2: ', '')
+----------------------+

('Sending', 'l-loader.bin', '...')
Done
```

There is no output from:
`sudo fastboot devices` so it looks like it is not detecting the device at all.

Any solutions to this issue?

Thanks in advance :)

**Comment by vchong** [comment]
The output of the ptable command is the same as the output of the python script?

Did you run the python script before executing the `sudo fastboot flash ptable ptable-aosp-8g.img` command? If so, and you've rebooted, then you need to run the python script again, to get it into fastboot mode again, before executing `sudo fastboot flash fastboot fip.bin`.

In any case, a reboot shouldn't be necessary between both `fastboot flash` commands. You should be able to just execute them consecutively. If you're following instructions on a page, it's probably outdated and needs to be updated.

**Comment by sdrobertw** [comment]
@atoaster 

Could you please provide a link to the docs you are using?

**Comment by sdrobertw** [comment]
Issue has been closed due to inactivity. If you are still experience problems, please open a new issue.

Thanks!
