### ISSUE TITLE
Problems with ConsumerEdition/DragonBoard-410c/

### ISSUE THREAD

**Issue by sjfricke** [96boards/documentation#225]
3 different things I have found of need of a quick fix and have commits ready for PR

- [Additonal Docs](https://github.com/96boards/documentation/tree/master/ConsumerEdition/DragonBoard-410c/AdditionalDocs)  is just not done in general in terms of having usable markdown links
- [Getting Started](https://github.com/96boards/documentation/tree/master/ConsumerEdition/DragonBoard-410c/GettingStarted) should have links in each kit towards the Power Adapter, USB Keyboard, and Mezz pages
- Bad image links in [Hardware User Manual](https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/HardwareDocs/HardwareUserManual.md) and [Vendo rDocs](https://github.com/96boards/documentation/tree/master/ConsumerEdition/DragonBoard-410c/VendorDocs)

**Comment by Mani-Sadhasivam** [comment]
@sjfricke Can you please submit PR?

Thanks for your contributions!

**Comment by Mani-Sadhasivam** [comment]
@sjfricke Any update on your PR?

Thanks

**Comment by sjfricke** [comment]
So idk how I must have missed the Feb 26 comment somehow. I guess looking at it I don't have the branch anymore, but looking at it, the two main things is that there is a missing image in [Vendor Docs](https://github.com/96boards/documentation/blob/master/consumer/dragonboard410c/vendor-docs/README.md) which I have no idea what it was supposed to be.

Also I realize now that the "Additional Docs" in almost every Consumer board is a useless page tbh, but I think that's beyond the scope of this issue

**Comment by daniel-thompson** [comment]
> Also I realize now that the "Additional Docs" in almost every Consumer board is a useless page tbh,
> but I think that's beyond the scope of this issue

Agree. Even it is was populated it would only be board images, etc so it should probably not be linked to.

**Comment by Mani-Sadhasivam** [comment]
@sjfricke Can you please submit PR for adding hyperlinks to getting started kits?

**Comment by sdrobertw** [comment]
Additional docs folder is intended to "future proof" the lineup; however, we could have also used something like "misc" just as well. The additional-docs folder is just there to hold anything that does not necessarily need to be made directly visible, but might be used somewhere else in the docs through a relative link or other.

No intention to actually make the additional-docs section visible on the front page.

Am going to close this issue now. If this issue has not yet been resolved, please re-open. 

Thank you for your contributions!
