### ISSUE TITLE
Extras/ContributionPolicy.md is over-zealous to the point of intimidation

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#228]
I am very curious about why we believe that having a policy requiring that users submit an Issue and be granted permission by a team member before submitting an PR helps to develop the community. Bluntly I would never waste my personal time contributing to an organisation with such an officious policy[1] (in fact even in my paid time this policy may act as in impediment to my own contributions[2]).

My immediate questions are

- Why are the policy goals not stated in the policy?
- How does this policy encourage contributions (assuming this is one of the policy goal)? 
- Has there been a significant problem with the quality of PRs submitted without corresponding Issues to date?
- Why aren't the comment sections within a PR sufficient to permit productive discussion of Issue-less PRs?
- What will we do if we receive a high quality easily reviewed PR without an Issue being submitted?

Daniel.

URL:  https://github.com/96boards/documentation/blob/master/Extras/ContributionPolicy.md

[1] I kept away from Zephyr for quite a while due to their similarly zealous contribution policy... happily they have relaxed somewhat since moving to github.
[2] Although I should admit that these are already fairly limited.

**Comment by sdrobertw** [comment]
@daniel-thompson This policy needs to be reworked 100%.

I think all of your points are valid and should be taken into account when re-launching a new contribution policy.

I will launch a doc and share.

Thanks!

**Comment by daniel-thompson** [comment]
The old contributions policy has been removed and replaced with a less offensive one.

Issue can be closed.
