### ISSUE TITLE
Problems with DragonBoard-410c/HardwareDocs/HardwareUserManual.md PMIC GPIO

### ISSUE THREAD

**Issue by sjfricke** [96boards/documentation#229]
In the [Hardward User Manual](https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/HardwareDocs/HardwareUserManual.md) It says the in [USB Host Ports](https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/HardwareDocs/HardwareUserManual.md#usb-host-ports) that it uses `USB_SW_SEL_PM, GPIO_4`. It also says in [Four User LEDs](https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/HardwareDocs/HardwareUserManual.md#four-user-leds) that `The other two User LEDs are driven by the PMIC via PM GPIO_1 and PM GPIO_2.`

According to the [Qualcomm Developer PDF](https://developer.qualcomm.com/download/db410c/gpio-pin-assignment.pdf) it should be:

- `PM_GPIO_01` == `USB_HUB_RESET_N`
- `PM_GPIO_02` == `USB_SW_SEL`
- `PM_GPIO_03` == `USB_LED_3_CTRL`
- `PM_GPIO_04` == `USB_LED_4_CTRL`

**Comment by Mani-Sadhasivam** [comment]
@sjfricke Looks like the QDN document is wrong! According to schematics, following is the pin mapping:

* PM_GPIO_1 - USR_LED_3_CTRL
* PM_GPIO_2 - USR_LED_4_CTRL
* PM_GPIO_3 - USB_HUB_RESET_N_PM
* PM_GPIO_4 - USB_SW_SEL_PM

Above holds true for [Hardware User Manual](https://github.com/96boards/documentation/blob/master/consumer/dragonboard410c/hardware-docs/hardware-user-manual.md#usb-host-ports).

@ndechesne your views?

Thanks for spotting!

**Comment by Mani-Sadhasivam** [comment]
@ndechesne Can you please provide your comment on this?

**Comment by Mani-Sadhasivam** [comment]
@ndechesne Ping on this issue!

**Comment by ndechesne** [comment]
sorry about the delay.. the schematics (and the DTS in upstream kernel) are correct.

**Comment by sdrobertw** [comment]
No changes necessary. Closing issue. Thanks!
