### ISSUE TITLE
"fastboot oem serialno" gets "FAILED (remote: OEM Command not recognised.)"

### ISSUE THREAD

**Issue by ninesunqian** [96boards/documentation#23]
Hello, I want to change the device id outputed by "fastboot devices". 
I did it as follows:
  1 built edk2 according to https://github.com/96boards/documentation/wiki/HiKeyUEFI . (modify the ptable as "sudo PTABLE=aosp-8g bash -x generate_ptable.sh")
  2 replaced the EFI/BOOT/fastboot.efi by new built AndroidFastbootApp.efi in boot_fat.uefi.img in https://github.com/96boards/documentation/wiki/HiKey-RP-Download#your-build-choice-1
  3 flashed l-loader.bin, ptable-linux.img, fip.bin of new built edk2
  4 flashed the new boot_fat.uefi.img
  5 flashed cache.img, system.img userdata-8gb.img in https://github.com/96boards/documentation/wiki/HiKey-RP-Download#your-build-choice-1

I got three problem:
  1 "fastboot oem serialno" gets "FAILED (remote: OEM Command not recognised.)"
  2 "fastboot getvar SerialNo" get "SerialNo: 
finished. total time: 0.001"
  3 kernel panic

How can I get the unique device serialno or set it, and resolve the kernel panic problem ?
Thanks very much !

**Comment by sdrobertw** [comment]
@fboudra any advice?

**Comment by docularxu** [comment]
ninesunqian, You should use this release:

http://builds.96boards.org/releases/reference-platform/components/uefi/16.06/release/hikey/

16.03 was considered obsolete.

-Guodong

**Comment by sdrobertw** [comment]
@ninesunqian 

Has this issue been resolved by using the newer release?

**Comment by sdrobertw** [comment]
Issue has been closed due to inactivity. If you are still experience problems, please open a new issue.

Thanks!
