### ISSUE TITLE
Problems with DragonBoard-820c

### ISSUE THREAD

**Issue by WeixiangXu** [96boards/documentation#243]
I am starting the board for the first time. 

1. I connect the DragonBoard 820c to my display with the HDMI cable. 
2. Then I connect the power supply to the DragonBoard.  (power light on)

But I get nothing on the monitor. Anything wrong?

**Comment by daniel-thompson** [comment]
This issue tracker is intended to report problems with the documentation rather than acting as a general technical support forum. Please use the support forums instead: https://discuss.96boards.org/c/products/dragonboard820c
