### ISSUE TITLE
Problem with "DragonBoard 820c Getting Started With Linux" 

### ISSUE THREAD

**Issue by WeixiangXu** [96boards/documentation#244]
when I'm flashing the device with [https://github.com/96boards/documentation/wiki/DragonBoard-820c-Getting-Started-With-Linux](url)
`sudo <PATH to qdl>/qdl prog_ufs_firehose_8996_ddr.elf rawprogram.xml patch.xml`

HELLO version: 0x2 compatible: 0x1 max_len: 1024 mode: 0
READ64 image: 13 offset: 0x0 length: 0x40
READ64 image: 13 offset: 0x40 length: 0x230
READ64 image: 13 offset: 0x1000 length: 0x168
READ64 image: 13 offset: 0x2000 length: 0x1000
... ...
READ64 image: 13 offset: 0x6b1b0 length: 0x1000
READ64 image: 13 offset: 0x6c1b0 length: 0x1000
READ64 image: 13 offset: 0x6d1b0 length: 0xff4
END OF IMAGE image: 13 status: 0
DONE status: 1
LOG: Binary build date: Jul 15 2016 @ 04:52:20
LOG: Chip serial num: 675104142 (0x283d458e)
LOG: Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc power benchmark read getstorageinfo getsha256digest erase peek poke 
LOG: Binary build date: Jul 15 2016 @ 04:52:20 
LOG: fh.attrs.Verbose is set to 0
LOG: Chip serial num: 675104142 (0x283d458e)
LOG: Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc power benchmark read getstorageinfo getsha256digest erase peek poke 
LOG: Calling usb_al_bulk_set_zlp_mode(FALSE) since ZlpAwareHost='0'
LOG: Calling hotplug_poll_device('UFS')
LOG: Storage device of type 'UFS' cannot be opened
LOG: storage_device_open() returned FALSE
LOG: ERROR 13: Line 1142: HANDLE_CONFIGURE_FAILURE

**Comment by daniel-thompson** [comment]
AFAICT this is a technical support matter rather than something that should be fixed in the documentation (it has been answered on the forum).
