### ISSUE TITLE
edk2-hikey installed but not shipped

### ISSUE THREAD

**Issue by f0c300** [96boards/documentation#26]
Hello!
 I'm getting this QA error building with poky for the hikey lemaker board.
I'm on branch krogoth for all my layers, and master for meta-96boards

```
edk2-hikey-0.0+AUTOINC+76c7cfcc22-bdec62eeb8-r0 do_package: QA Issue: edk2-hikey: Files/directories were installed but not shipped in any package:
  /usr
  /usr/lib
  /usr/lib/edk2
  /usr/lib/edk2/bl1.bin
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
edk2-hikey: 4 installed and not shipped files. [installed-vs-shipped]
ERROR: edk2-hikey-0.0+AUTOINC+76c7cfcc22-bdec62eeb8-r0 do_package: Fatal QA errors found, failing task.
ERROR: edk2-hikey-0.0+AUTOINC+76c7cfcc22-bdec62eeb8-r0 do_package: Function failed: do_package
ERROR: Logfile of failure stored in: /home/yocto/hikey-build/tmp/work/hikey-poky-linux/edk2-hikey/0.0+AUTOINC+76c7cfcc22-bdec62eeb8-r0/temp/log.do_package.5204
ERROR: Task 77 (/home/yocto/poky/meta-96boards/recipes-bsp/uefi/edk2-hikey_git.bb, do_package) failed with exit code '1
```

as a quick fix I added
`FILES_${PN} += "${libdir}/edk2/bl1.bin"` 
to the recipe.

As a side-note, when it fails, I have to rebuild (deploy) grub because grubaarch64 gets deleted during the do_deploy, this isn't really an issue but I thought it could be mentioned.

ps : I'm sorry I just saw I opened the issue in documentation, is it possible to move it to the main page or should I delete and recreate one?

**Comment by sdrobertw** [comment]
@koenkooi Can you help with this issue?
