### ISSUE TITLE
Problem with IoTEdition/carbon/build/LinuxBuild/BuildDisco.md

### ISSUE THREAD

**Issue by gokaksantosh** [96boards/documentation#263]
unable to do git clone for the repo provided, I am getting an error saying that this is not a get repository.
I was trying to build disco example.

Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/IoTEdition/carbon/build/LinuxBuild/BuildDisco.md.html

**Comment by ric96** [comment]
Hi, 
This seems to be the correct repo. 

https://github.com/zephyrproject-rtos/zephyr

Thanks for notifying, we'll change the documentation with the correct link.

**Comment by Mani-Sadhasivam** [comment]
@ric96, please update the guide with new cmake instructions.

**Comment by sdrobertw** [comment]
Thank you @ric96 for the fix!

@gokaksantosh please see https://github.com/96boards/documentation/pull/298 - now merged
