### ISSUE TITLE
Problem with ConsumerEdition/B2260/HardwareDocs/HardwareUserManual.md

### ISSUE THREAD

**Issue by danrue** [96boards/documentation#267]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/ConsumerEdition/B2260/HardwareDocs/HardwareUserManual.md.html

All image links are broken

**Comment by Mani-Sadhasivam** [comment]
Hi @danrue,

Looks like the image links are fixed: https://www.96boards.org/documentation/consumer/b2260/hardware-docs/hardware-user-manual.md.html

Please close the issue if everything seems to be correct!
