### ISSUE TITLE
SPI Image "boot-db410c-spi.img" not working

### ISSUE THREAD

**Issue by cba16** [96boards/documentation#27]
I downloaded this image on the link given here but my Dragonboard doesn't detect anything when I try to boot it with this image on the SD Card. Is there any additional step to do?

**Comment by sdrobertw** [comment]
@rsalveti

**Comment by sdrobertw** [comment]
@cba16 

boot-db410c-spi.img is just the boot image (it is not an SD card image), I would suggest using fastboot to flash this image to your board.

1. boot your board into fastboot mode
2. flash boot-db410c-spi.img to board via USB to MicroUSB

$ sudo fastboot devices     (to make sure board is detected)
$ sudo fastboot flash boot boot-db410c-spi.img

---

Where did you get this image from? I am guessing here?:
https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/Configuration/EnableSPI.md

**Comment by sdrobertw** [comment]
Issue has been closed due to inactivity. If you are still experience problems, please open a new issue.

Thanks!
