### ISSUE TITLE
Updated consumer/bubblegum-96/hardware-docs/SoC_bubblegum96.pdf

### ISSUE THREAD

**Issue by Alberto1398** [96boards/documentation#281]
The current version of the SoC datasheet for the bubblegum-96 on this repository does not have a proper index which makes it extremely difficult to read, surfing on the internet i have found an updated datasheet that has this feature.

I found it on the Cubietech ftp server:
http://dl.cubieboard.org/part/S900/

[S900_Datasheet_v1.2.pdf](https://github.com/96boards/documentation/files/1733384/S900_Datasheet_v1.2.pdf)

Anyways since there is updated documentation available, why not update it? ;-)

**Comment by sdrobertw** [comment]
@Alberto1398 Let me look into this and get back to you. If this is in fact a newer version of the datasheet, we will of course update :)

Thanks for your input!

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Can you please provide suggestion?

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Any update on this?

**Comment by Mani-Sadhasivam** [comment]
More recent version of the datasheet will be publicly available from Actions soon. So we can update it once released. Closing this issue for now!
