### ISSUE TITLE
Redirects not working with consumer/dragonboard410c/installation/linux-sd-boot.md

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#295]
The redirect from https://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Installation/LinuxSDBoot.md.html is not working correctly.

For example this link on the forum has been borked by the recent renamefest:
https://discuss.96boards.org/t/clone-a-dragonboard-to-other-dragonboard-units/971/12

We're seeing this a lot... and its leading people to assume that relatively recent topics (Jan in this case) are no longer up to date.

URL:  https://www.96boards.org/documentation/consumer/dragonboard410c/installation/linux-sd-boot.md.html

**Comment by shovanuk** [comment]
@ric96 @kylekirkby Please check the redirect files

**Comment by Mani-Sadhasivam** [comment]
Issue is fixed and redirect is working now! Thanks @daniel-thompson for reporting.
