### ISSUE TITLE
Enabling SPI on Dragonboard 410c with SPIDEV won't work

### ISSUE THREAD

**Issue by cba16** [96boards/documentation#30]
Hi,
I'm trying to eenable SPI on my Dragonboard but it doesn't work.
I followed the instruction to use SPIDEV, but on the step git clone -n http://git.linaro.org/landing-teams/working/qualcomm/kernel.git it starts to download and then stops, not finishing, and I can't continue to the next steps without it downloaded.
Why does this happen? How can I fix it and use my SPI?
Thanks

**Comment by sdrobertw** [comment]
@cba16 

Have you reference this doc yet?

https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/Configuration/EnableSPI.md

**Comment by sdrobertw** [comment]
@cba16 

I believe you are having storage or networking issues. I was able to clone kernel.git with out any issues onto two separate machines. 

I would suggest checking to make sure the machine you are cloning onto has enough storage. 

Please let us know if you are still having problems.

**Comment by sdrobertw** [comment]
@cba16 

Are you still experiencing this issue?

**Comment by cba16** [comment]
Hi,
I managed to install it finally but I'm not able to run SPIDEV still. When I connect a sensor board there just isn't anything coming in by SPI. Do I need to trigger it somehow else?

**Comment by sdrobertw** [comment]
@rsalveti 

So you have any advice on this issue?

**Comment by rsalveti** [comment]
Make sure the spi-test is working as expected, then the setup will depend on your device and your connect. Any additional detail about your setup would already help.

**Comment by vchong** [comment]
@cba16 Can you please check first your distro.config to see if CONFIG_SPI_SPIDEV=y? If not, please try setting it and rebuilding.

**Comment by vchong** [comment]
@cba16 CONFIG_SPI_SPIDEV=m works as well, in which case you'll have to run `insmod spidev` or `modprobe spidev` before testing.

**Comment by araffucci** [comment]
In addition to making sure I have spidev in the kernel, I had to add device under each SPI in the device tree (arch/arm64/boot/dts/qcom/apq8016-sbc.dtsi): 

                spi@78b7000 {
		/* On High speed expansion */
			label = "HS-SPI1";
			status = "okay";

			spidev@0 {
				compatible = "spidev";
				spi-max-frequency = <500000>;
				reg = <0>;
			};
		};
		
                spi@78b9000 {
		/* On Low speed expansion */
			label = "LS-SPI0";
			status = "okay";

			spidev@0 {
				compatible = "spidev";
				spi-max-frequency = <500000>;
				reg = <0>;
			};
		};
