### ISSUE TITLE
OpenCL

### ISSUE THREAD

**Issue by MattyBoy4444** [96boards/documentation#32]
Does the linux image have accelerated OpenCL/Drivers?

**Comment by ndechesne** [comment]
which Linux image, and for which board?

**Comment by MattyBoy4444** [comment]
Bubblegum-98, Debian or Ubuntu Core.

**Comment by sdrobertw** [comment]
@ldts Can you help with this issue?

**Comment by ProfFan** [comment]
OpenCL support is included by installing the vendor graphics driver.

**Comment by sdrobertw** [comment]
@MattyBoy4444 

Can we close this issue?

**Comment by MattyBoy4444** [comment]
I am pretty sure you can't just "get" the OpenCL driver for Mali Graphics chips.   I do not one of these boards, would someone see if they can get it and let us know?  I use ODROID and they include the OpenCL driver in their images.

**Comment by daniel-thompson** [comment]
Bubblegum96 does not have MALI graphics, is has a PowerVR GPU.

AFAIK there is no GPU support (OpenGL or OpenCL) in the debian-based snapshot images for this board at http://builds.96boards.org/snapshots/ . I'm afraid I don't know that status of the ubuntu-core builds, IIRC these were produced by Canonical.

**Comment by ProfFan** [comment]
@daniel-thompson OpenCL works perfectly for me on Debian after installing the drivers in https://github.com/96boards-bubblegum/s900-gpu-binary

**Comment by daniel-thompson** [comment]
In truth I'd *completely* forgotten about the extra GPU repo. I only remembered that we never quite set up the CI to integrate it out-of-the-box in the debian build.

So, many thanks @ProfFan, epic news! Doubly so because I think that makes BG96 the only currently shipping 96Board that supports OpenCL without requiring Android.

**Comment by luckycat889** [comment]
I am also interested in BG and opencl on debian. 
ProfFan, are you using opencl tools only from debian repos?
Perhaps, I am not the only one curious about this; would you mind, posting a super-quick howto on this?

Thanks,

**Comment by ProfFan** [comment]
Maybe I will do a short blog for a summary in recent days. @luckycat889

**Comment by luckycat889** [comment]
@ProfFan, sounds good.
I sort of have everything up and running after installing s900-gpu-binary.
However, I don't see it including the headers for CL/OpenCL.h and such. It does seem to include opengl headers though

Appreciate any advice you might have,
Thanks,

**Comment by ProfFan** [comment]
@luckycat889 You can simply `apt-get install opencl-headers` to get them.

**Comment by sdrobertw** [comment]
May we close this issue? @ProfFan @daniel-thompson @luckycat889

**Comment by ProfFan** [comment]
LGTM

**Comment by sdrobertw** [comment]
Thank you, @ProfFan !
