### ISSUE TITLE
Problem with consumer/dragonboard820c/getting-started/README.md

### ISSUE THREAD

**Issue by cezmen** [96boards/documentation#325]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/dragonboard820c/getting-started/

"If you are already familiar with the **i.MX7** 96 board" ... Did you mean "DragonBoard 820c", instead of "i.MX7"?  :)

**Comment by daniel-thompson** [comment]
Thanks for the report!
