### ISSUE TITLE
Android SD Install Image Not Working

### ISSUE THREAD

**Issue by davidbcoulson** [96boards/documentation#33]
All the steps to add Android to the board were followed (several times).  I believe there is an issue with the Android Install img file.  Perhaps the version on this site is missing boot files.

**Comment by sdrobertw** [comment]
@davidbcoulson 

Sorry you are having issues with the Android install images provided, I would be glad to help fix this. Could you please provide the following information:

1. Which 96Boards are you using?
2. Please provide a link to the instruction set(s) you are following

If you can provide this information, I will be able to check links and test instructions to make sure everything is up to date and working.

Thank you!

**Comment by sdrobertw** [comment]
@davidbcoulson 

Has this issue been resolved?

**Comment by sdrobertw** [comment]
Issue has been closed due to inactivity. If you are still experience problems, please open a new issue.

Thanks!
