### ISSUE TITLE
any plan to split the documents in different repo for better maintenance?

### ISSUE THREAD

**Issue by vamrs** [96boards/documentation#334]
Each board should have its own documents repos and managed with git submodules, is that in consideration? The main reason is if we want to quote the whole documentation of specified board, we will have to quote the whole 96boards documentation.

**Comment by sdrobertw** [comment]
@vamrs We can definitely consider this. We can bring this up with 96Boards and Website team, and other partners to see if it would be of interest. 

Let's talk more about this at Connect. I like the suggestion.

**Comment by ndechesne** [comment]
i am not claiming that splitting is a good idea.. but if we ever break things into 'boards', then i would like to make sure that we don't split up db410c from db820c and keep them together, e.g. to make a 'dragonboard' family doc.

**Comment by sdrobertw** [comment]
This issue has already been addressed by making the following families:

[HiKey](https://github.com/96boards/documentation/tree/master/consumer/hikey)
[DragonBoard](https://github.com/96boards/documentation/tree/master/consumer/dragonboard)
[Rock](https://github.com/96boards/documentation/tree/master/consumer/rock)

Each family equipped with sections to address overlapping content and individual sections for board specific content.
