### ISSUE TITLE
hikey960 board does not work with opencl

### ISSUE THREAD

**Issue by pcub** [96boards/documentation#338]
Hello, I have hikey960 boards, it has android os in it. However, when I run opencl program, it say
terminate called after throwing an instance of 'cl::Error’
what(): clGetDeviceInfo.

I download mali-450_r7p0-00rel0_android-6.0_1.tar.gz from https://developer.arm.com/products/software/mali-drivers/user-space and pushed libOpenCL.so to hikey. But also get same error shown above.
Can you give me more information about how to give it work on opencl with hikey960?
Thanks you

**Comment by ric96** [comment]
@pcub
Hi, this repository's issue section is only to deal with issues with the website.
You can ask this question on the forum, https://discuss.96boards.org
Jusy tag me @ric96 and I'll be more than willing to help out.
Thanks.
