### ISSUE TITLE
Github Rendering on Website

### ISSUE THREAD

**Issue by ShovanSargunam** [96boards/documentation#34]
The following page is not rendering properly 
http://www.96boards.org/db410c-getting-started/AdditionalDocs/UserManual.md/

Github page can be viewed here
https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/AdditionalDocs/UserManual.md

**Comment by sdrobertw** [comment]
@ShovanSargunam 

I am on it, thanks for pointing this out.

**Comment by sdrobertw** [comment]
This issue has been resolved, please open a new issue for any further website rendering issues.

Thanks!
