### ISSUE TITLE
Problem with db410c Linux Host fastboot install documentation?

### ISSUE THREAD

**Issue by tdhammer** [96boards/documentation#342]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/dragonboard410c/installation/linux-fastboot.md.html

In Step 1 - using a distro manager -
not sure it applies to Debian or when it might have changed in Ubuntu, but in my 16.04 (Xenial) is not finding android-tools but it does find android-tools-fastboot.

I am not a package expert by any stretch, but it is confusing since launchpad indicates that there is an android-tools package:
https://launchpad.net/ubuntu/+source/android-tools

while Ubuntu packages shows the tools each individually:
https://packages.ubuntu.com/search?keywords=android-tools&searchon=names&suite=all&section=all

**Comment by sdrobertw** [comment]
@tdhammer Thanks for bringing this up! We will look into this asap. @ric96 is on the case.

**Comment by tdhammer** [comment]
@ric96 - FWIW, I made a couple updates to fastboot commands and submitted a pull request for those changes.

**Comment by ric96** [comment]
@tdhammer 
it should be
```
sudo apt install android-tools*
```
this will install adb fastboot and mkbootimg etc

**Comment by tdhammer** [comment]
Thanks @ric96 
If you know someone who has 14.04 (trusty), it might be worthwhile to have them check- it looks like the package split occurred by that release and it will be around for at least a couple more years...
