### ISSUE TITLE
Problem with _documentation/consumer/hikey960/downloads/debian.md

### ISSUE THREAD

**Issue by susmithagankidi** [96boards/documentation#384]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/hikey960/downloads/Debian.md.html

The links for fastboot images take me no where

**Comment by Mani-Sadhasivam** [comment]
@susmithagankidi Hikey960 docs are being worked on by the 96Boards team. Please stay tuned for the update. We will link this issue when the pull request gets submitted.

Thanks!

**Comment by Mani-Sadhasivam** [comment]
@daniel-thompson @b49020 is a member of documentation repo. So, I can't add him as an assignee!

**Comment by b49020** [comment]
@Mani-Sadhasivam @daniel-thompson I have created #448 pull request to add debian download and installation steps on hikey960. Please review.

**Comment by Mani-Sadhasivam** [comment]
Closing this issue since the HiKey960 docs are live now!
