### ISSUE TITLE
5.2.1 Installing ADB Drivers

### ISSUE THREAD

**Issue by cyberh0me** [96boards/documentation#4]
the requested change of "android_winusb.inf" does not work as the installation fails with "The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering"

solution either sign the driver or disable driver signature verification...

**Comment by cyberh0me** [comment]
another issue even with the changes is windows not able to find a driver...
the board is from Arrow "USB\VID_05C6&PID_9091&MI_01" and this item is not included in your requested changes

**Comment by sdrobertw** [comment]
@cyberh0me 

If this is a comment with regard to the Coursera documentation, please provide the Course#/name and module you are on. 

If not, please provide links to the documents you are referring to.

Thanks.

**Comment by cyberh0me** [comment]
sorry, documentation / dragonboard410c / AndroidUserGuide_DragonBoard.pdf

**Comment by sdrobertw** [comment]
@cyberh0me 

96Boards didn't actually make that document. That being said, we are in the process of extracting, fixing, and consolidating all documentation, especially from documents like this one. It might take some time, though I will make sure this issue stays on the list. Where you able to work around the issue, even with bad instructions? 

Thanks

**Comment by cyberh0me** [comment]
i know you did not make that documents but qualcomm says explicit all support and issues are handled from 96boards
meanwhile i stopped to work with that board family based on technical troubles, documentation issues, time wasting things like this
