### ISSUE TITLE
Does hekey have "Watermark technique on ARM processors"? 

### ISSUE THREAD

**Issue by kettyjun** [96boards/documentation#43]
Does hikey have "Watermark technique on ARM processors"? Or is there any details Like "“i.MX53 Reference Manual with fusemap addendum" ?

**Comment by docularxu** [comment]
Yes, the chip (hi6220) has fuse inside. However, this is not open to the public. It's one-time writable and is written in the production phase.

**Comment by kettyjun** [comment]
Oh,Thanks

**Comment by kettyjun** [comment]
@docularxu Oh, thanks!

**Comment by sdrobertw** [comment]
@kettyjun 

Has this issue been resolved?
