### ISSUE TITLE
Problems with _documentation/consumer/mediatekx20/additional-docs/README.md

### ISSUE THREAD

**Issue by cyrozap** [96boards/documentation#476]
URL:  https://www.96boards.org/documentation/consumer/mediatekx20/additional-docs/

Looks like there was a [copy/paste error](https://github.com/96boards/documentation/pull/445/files#diff-301ba33c9f33c4c467e084982d969e17R18) in #445, and the "Register Table Part 1" link is a duplicate of the "Functional Specifications" one.

Separately, a minor nitpick: The spacing on the link titles is a little inconsistent. e.g., "MT6797LTE-A Smartphone..." and "MT6797 LTE-ASmartphone..." should be "MT6797 LTE-A Smartphone...", and "...Board(Part I)" should be "...Board (Part I)".

**Comment by Mani-Sadhasivam** [comment]
@cyrozap Thanks a lot for reporting! I have submitted the fix #477.
