### ISSUE TITLE
Hikey 970

### ISSUE THREAD

**Issue by karishmabava** [96boards/documentation#479]
Hi,
Hikey 970 has ethernet network droupouts after 20-30 mins in developers mode. Also the connection from USB C to USB C (Mac) gives device recognition issues, where the device keeps being detected and undetected for a long time.

Please help!

Thanks,
Karishma Bava

**Comment by Mani-Sadhasivam** [comment]
Hi @karishmabava,

Can you please post your issue in [96Boards Forum](https://discuss.96boards.org/c/products/hikey970)? Documentation issues are meant to specify any issue with the board documentation like unclear documentation, broken links etc...and we handle all technical issues through forum.

Thanks for your time.
