### ISSUE TITLE
Problem with _documentation/consumer/hikey970/downloads/README.md

### ISSUE THREAD

**Issue by karishmabava** [96boards/documentation#485]
Hi,

I was reading the documentation and it says that Hikey 970 comes pre installed with Linux. But when I switched on my Hikey 970 it had Android on it. How can I switch it to Linux or where can I get ubuntu img to flash.

Thank you

**Comment by Mani-Sadhasivam** [comment]
Hi @karishmabava,

HiKey970 is supposed to come with Linux but for some reasons they made Android support first and then working on Linux later. Currently the Linux images are under development, primarily focussed on Debian and I don't think there is any plan to support Ubuntu.

You ca find the kernel source for HiKey970 in below repo:
https://github.com/96boards-hikey/linux/tree/hikey970-v4.9
