### ISSUE TITLE
Problem while Flashing Hikey 970

### ISSUE THREAD

**Issue by karishmabava** [96boards/documentation#491]
Hi,

I am having problem while flashing linux debian on hikey 970. Please help me out.

sudo ./recovery-flash.sh /dev/ttyXRUSB0
Config name: /home/parallels/tools-images-hikey970/config
Port name: /dev/ttyXRUSB0
0: Image: ./sec_usb_xloader.img Downalod Address: 0x22000
1: Image: ./sec_usb_xloader2.img Downalod Address: 0x60049000
2: Image: ./l-loader.bin Downalod Address: 0x16800000
Serial port open successfully!
Start downloading ./sec_usb_xloader.img@0x22000...
file total size 122880
downlaod address 0x22000
^C< waiting for device >

**Comment by Mani-Sadhasivam** [comment]
Hi @karishmabava,

As I said before, please forward your issue to [96Boards Forum](https://discuss.96boards.org/c/products/hikey970). We don't take technical issues through documentation repo.

Thanks for understanding!
