### ISSUE TITLE
Fix for couple minor issues in wiki

### ISSUE THREAD

**Issue by pietrushnic** [96boards/documentation#5]
Hi 96boards,
I did minor fixes to JTAG-on-HiKey wiki page. Feel free to merge [this commit](https://github.com/3mdeb/96boards-docs-wiki/commit/3e02024ac4f32800d3bc5f4a0b31a9da8dba3073).

**Comment by sdrobertw** [comment]
I will review changes. Thank you very much for your contribution!

Stay tuned.

**Comment by sdrobertw** [comment]
I would be glad to merge. Could you please send a pull request for these changes.

Thank you!

**Comment by pietrushnic** [comment]
@sdrobertw how and where I can send pull request for wiki page ? IIUC PRs doesn't work against GitHub wiki. Am I missing something ?

**Comment by sdrobertw** [comment]
You're right. Since there is no way to submit a pull request for the wiki, we have merged your commit. Sorry for the confusion.

Thanks again!
