### ISSUE TITLE
Ticket for Issue in 96Boards Documentation

### ISSUE THREAD

**Issue by kylekirkby** [96boards/documentation#507]
This is just a report of error in board documentation.

Hardware User Manual (https://www.96boards.ai/documentation/consumer/hikey970/hardware-docs/files/hikey970-user-manual.pdf)

In section 1.3.7 Antenna connector states that:

"The HiKey board is equipped with a TI WL1835MOD WLAN Baseband Processor [...]

It should be:

"The HiKey board is equipped with a TI WL1837MOD WLAN Baseband Processor [...]

Rationale:

WL1835MOD is unlikely, it doesn't support wireless AC.

Also schematics (https://www.96boards.ai/documentation/consumer/hikey970/hardware-docs/files/hikey970-schematics.pdf) mentions on page 22 (WIFI/BT) WL1837MOD.

Hi,This is just a report of error in board documentation.Hardware User Manual (https://www.96boards.ai/documentation/consumer/hikey970/hardware-docs/files/hikey970-user-manual.pdf)In section 1.3.7 Antenna connector states that:"The HiKey board is equipped with a TI WL1835MOD WLAN Baseband Processor [...]It should be:"The HiKey board is equipped with a TI WL1837MOD WLAN Baseband Processor [...]Rationale:WL1835MOD is unlikely, it doesn't support wireless AC.Also schematics (https://www.96boards.ai/documentation/consumer/hikey970/hardware-docs/files/hikey970-schematics.pdf) mentions on page 22 (WIFI/BT) WL1837MOD.

Kind regards,

Bartosz Meglicki
--

**Comment by Mani-Sadhasivam** [comment]
Hi,

This looks like a copy paste error in the user manual. Since the manual is inherited from HiKey which uses WL1835, they forgot to replace it. The correct part number is WL1837.

@sdrobertw Can we ask HiSilicon to change the content in User manual?

Thanks for reporting!

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Any update on this?

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam Best we tag @docularxu here and see if he has anything to add before we start pinging HiSi folks.

Thanks.
