### ISSUE TITLE
 After flashing and rebooting the board, it is booting fine and it is working fine. But I cannot find /dev/v4l-subdev.  only by-path is listed under v4l.. What should I do to get the subdevices? 

### ISSUE THREAD

**Issue by GargiGeetha** [96boards/documentation#514]
I did every steps as per the instructions mentioned in the documentation. After flashing and rebooting the board, it is booting up fine and it is working fine. But I cannot find /dev/v4l-subdev. only by-path is listed under v4l.. What should I do to get the subdevices?
URL:  https://www.96boards.org/documentation/consumer/dragonboard410c/installation/linux-fastboot.md.html

**Comment by Mani-Sadhasivam** [comment]
Hi @GargiGeetha,

Please forward your issue to the [96Boards Forum](https://discuss.96boards.org/c/products/dragonboard410c). Documentation issue is only for issue related to board documentation.

Thanks!

**Comment by GargiGeetha** [comment]
Please help to solve this issue. v4l-subdevices is not listed under /dev/v4l.
How will I get it?

**Comment by Mani-Sadhasivam** [comment]
Hi @GargiGeetha,

As I said before, please forward your issue to the 96Boards Forum. Your issue will get sorted out quickly when you ask it in forum. We don't take technical issues through documentation repo.

Hope you understand!

Thanks
