### ISSUE TITLE
 Could not load /vendor/lib/hw/android.hardware.drm@1.0-impl.so from sphal namespace: dlopen failed: library "android.hardware.drm@1.0.so" not found.

### ISSUE THREAD

**Issue by rabi2017** [96boards/documentation#516]
Downloaded source code : https://source.android.com/setup/build/devices
Device: HiKey 960 board.

Trying to play a drm protected content and getting the following error.

**07-02 09:39:26.985  2405  3762 E vndksupport: Could not load /vendor/lib/hw/android.hardware.drm@1.0-impl.so from sphal namespace: dlopen failed: library "android.hardware.drm@1.0.so" not found.
07-02 09:39:26.985  2405  3762 E ServiceManagement: Failed to dlopen android.hardware.drm@1.0-impl.so: unknown error
07-02 09:39:26.985  2405  3762 E DrmHal  : Failed to find any drm factories**

Any help??

Thanks in advance.

**Comment by Mani-Sadhasivam** [comment]
Hi @rabi2017,

Please forward your issue to the [96Boards Forum](https://discuss.96boards.org/c/products/hikey960). Your issue will get sorted out quickly when you ask it in forum. We don't take technical issues through documentation repo.

Hope you understand!

Thanks,
Mani
