### ISSUE TITLE
The connection between HikeyBoard and PC is not stable

### ISSUE THREAD

**Issue by leesera** [96boards/documentation#52]
I try to set linking J15 1-2 and 3-4 pins of Board and connect the PC and my board.

and I try to find the /dev/ttyUSB0 on my PC.

But the /dev/ttyUSB0 is appeared few seconds(1~2) and then disappeared.

So when I put this command ` ./flash-all.sh /dev/ttyUSB1`
the output is like this
+----------------------+
 Serial:  /dev/ttyUSB0
 Image1:  ./l-loader.bin
 Image2:
+----------------------+

Sending ./l-loader.bin ...
Traceback (most recent call last):
  File "./hisi-idt.py", line 263, in <module>
    main(sys.argv[1:])
  File "./hisi-idt.py", line 260, in main
    burnboot('hi3716cv200', dev, img1, img2)
  File "./hisi-idt.py", line 202, in burnboot
    downloader.download(filename1, filename2)
  File "./hisi-idt.py", line 187, in download
    self.senddata(data,self.bootheadaddress[self.chip])
  File "./hisi-idt.py", line 173, in senddata
    self.senddataframe(seq,data[(seq-1)*self.MAX_DATA_LEN:seq*self.MAX_DATA_LEN])
  File "./hisi-idt.py", line 156, in senddataframe
    self.sendframe(data,32)
  File "./hisi-idt.py", line 103, in sendframe
    self.s.flushOutput()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 569, in flushOutput
    self.reset_output_buffer()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 582, in reset_output_buffer
    termios.tcflush(self.fd, termios.TCOFLUSH)
termios.error: (5, 'Input/output error')

or
show 
android out dir:./../../../..//out/target/product/hikey
+----------------------+
 Serial:  /dev/ttyUSB0
 Image1:  ./l-loader.bin
 Image2:
+----------------------+

Sending ./l-loader.bin ...
Done
and not finishing.

is my board poor?

**Comment by vchong** [comment]
Note that in https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/LinuxFactoryImage.md, it is mentioned that `The HiKey board will remain in USB load mode for 90 seconds from power up. If you take longer than 90 seconds to start the install then power cycle the board before trying again.` Did you maybe wait more than 90 seconds? Also check to see if there's any mention of `/dev/ttyUSB0` in `dmesg`.

**Comment by leesera** [comment]
@vchong Thank you for helping me :)
I found the reason about that situation. I used 220V power adapter for hikey board. After changing the adapter to 110V, my PC recongnizes the ttyUSB0 well.

**Comment by sdrobertw** [comment]
@leesera 

Has this issue been resolved?

**Comment by leesera** [comment]
@sdrobertw yes:) I will close this issue
