### ISSUE TITLE
Problem with _documentation/mezzanine/sensors-mezzanine/README.md

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#524]
The rendered version of this page needs review.

There is litter above some of the images (links to Robert's private github instead of the underlying image) and most of the links have not auto-linkified (forcing user to copy 'n paste).

URL:  https://www.96boards.org/documentation/mezzanine/sensors-mezzanine/

**Comment by sdrobertw** [comment]
Assigning this to @ric96 

Thanks, @daniel-thompson

**Comment by kylekirkby** [comment]
Updated in the above PR
