### ISSUE TITLE
Docker instructions are for Docker 1.9; current release is Docker 1.13

### ISSUE THREAD

**Issue by vielmetti** [96boards/documentation#53]
The docs need a refresh for Docker, as the current release is Docker 1.13 and the existing docs reference an old Docker 1.9 release.

**Comment by fboudra** [comment]
none of the distribution officially supported  (Debian Jessie and CentOS 7) are shipping with 1.13.

In addition, I don't think the docker instuctions between 1.9 and 1.13 are different. How do they need a refresh?

**Comment by sdrobertw** [comment]
This issue has been inactive without response from @vielmetti 

If you are still having a problem, please open a new issue.

Thanks!
