### ISSUE TITLE
Hikey SD card boot instructions do not work / are incomplete

### ISSUE THREAD

**Issue by ubitux** [96boards/documentation#545]
Page: https://github.com/96boards/documentation/blob/master/consumer/hikey/hikey620/installation/linux-sd-boot.md

That page doesn't document the jumper configuration

Also while booting, nothing happens on HDMI when plugging the micro-sd. Meanwhile, the serial uart0 interface only shows the following:

```
debug EMMC boot: print init OK
debug EMMC boot: send RST_N .
febug EMMC boot: s4art eMMC boot......
load fastboot1!
```

Only the green LED904 seems on (not blinking).

**Comment by Mani-Sadhasivam** [comment]
@ubitux Thanks for reporting! Perhaps this issue can be moved to the [96Boards Forum](https://discuss.96boards.org/c/products/hikey) for better visibility to the community.

**Comment by ubitux** [comment]
Cross-posted at https://discuss.96boards.org/t/hikey-sd-card-boot/5396

I might be doing something wrong, but the documentation is incomplete so I'd still keep that issue open.

**Comment by Mani-Sadhasivam** [comment]
I will verify the instructions on my hikey this week.

**Comment by sdrobertw** [comment]
@ubitux thank you for posting this issue in the forum! Hopefully it can be addressed there. I will close this issue now.

If you feel the issue was not solved, please feel free to re-open this issue, or simply start a new one.

Thanks!
