### ISSUE TITLE
No schematic diagram for Dragonboard 820C

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#552]
The hardware docs does not include a schematic diagram for 820C. This is IIRC a certification requirement for a board (and its also very inconvenient).

URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard820c/hardware-docs/

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Any plan on getting the schematic?

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam @daniel-thompson 

should be fixed with this PR: https://github.com/96boards/documentation/pull/679
