### ISSUE TITLE
Problem with _documentation/consumer/rock/downloads/ubuntu.md

### ISSUE THREAD

**Issue by GuillermoCallaghan** [96boards/documentation#556]
Hi, I recently downloaded the Ubuntu 16.04 Server arm64 image and installed it, after playing with it for a while I found out the username and password, I think it should be visible on the page (username: rock password:rock). I did not try with other images, but the same would apply.
Thanks.
URL:  https://www.96boards.org/documentation/consumer/rock/downloads/ubuntu.md.html

**Comment by Mani-Sadhasivam** [comment]
@vamrs Can you please take a look at this issue?
