### ISSUE TITLE
Problem with _documentation/consumer/hikey/hikey970/build/aosp.md

### ISSUE THREAD

**Issue by dashsriram** [96boards/documentation#567]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/hikey/hikey970/build/aosp.md.html

The source code is not building and giving the following error: 
build/make/core/Makefile:28: error: overriding commands for target `out/target/product/hikey970/system/vendor/lib/libc_secshared.so’, previously defined at build/make/core/base_rules.mk:418

**Comment by ric96** [comment]
@Mani-Sadhasivam no updates really, on second thoughts shouldn't this be moved to the forum. Build steps seem fine.

**Comment by ric96** [comment]
AOSP now builds, but the fix is still unmerged
https://github.com/96boards-hikey/aosp-device-linaro-hikey/pull/13
