### ISSUE TITLE
Dragonboard GPT documentation is missing

### ISSUE THREAD

**Issue by jaimeyu** [96boards/documentation#57]
I'm looking for the documentation to the Dragonboard GPT but all the links are non functioning. Here is a google cache of the page: http://webcache.googleusercontent.com/search?q=cache:il8ZmnqIC0EJ:www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Configuration/GPT.md/+&cd=1&hl=en&ct=clnk&gl=ca

Here is the page not working: http://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Configuration/GPT.md/

This wiki page says it moved but 404's: https://github.com/96boards/documentation/wiki/Dragonboard-410c-GPT

The[ tools are still available](https://git.linaro.org/landing-teams/working/qualcomm/db-boot-tools.git/tree/) so I think the documentation pages must have gotten deleted.

**Comment by ndechesne** [comment]
the actual page seems to be here now:
http://www.96boards.org/documentation/ConsumerEdition/DragonBoard-410c/Guides/GPT.md/
I fixed the bad link in the wiki as well.
sorry about the troubles..
