### ISSUE TITLE
sensors-mezzanine: Documentation is out-of-date versus latest mraa/upm packages

### ISSUE THREAD

**Issue by b49020** [96boards/documentation#573]
Hi,

"documentation/mezzanine/sensors-mezzanine/Readme.md" needs to be updated corresponding to MRAA (v1.9.0) and UPM (v1.6.0) Debian packages upgrade.

Regards,
Sumit

**Comment by Mani-Sadhasivam** [comment]
@b49020 Thanks a lot for reporting! Btw, feel free to submit a PR for fixing that, otherwise we will take it up.

**Comment by b49020** [comment]
@Mani-Sadhasivam I would be happy to create a PR but actually I don't have sensors mezzanine and other modules to test the examples.

**Comment by Mani-Sadhasivam** [comment]
@b49020 No worries. @ric96 Will take care of this. Thanks once again!

**Comment by ric96** [comment]
@Mani-Sadhasivam @b49020 can you tell which exact/line or paragraph this is, I don't see us mentioning any specific version of mraa here.

**Comment by b49020** [comment]
@ric96 Actually its not about mraa version info but regarding outdated examples corresponding to upm v1.6.0 python libraries. One of outdated example is mentioned [here](https://discuss.96boards.org/t/mraa-and-upm-not-working-together/5157/7?u=sumit.garg).

**Comment by Mani-Sadhasivam** [comment]
@ric96 We need to test all the examples mentioned in the README or I would recommend to just point to the upstream UPM example and modify the instructions accordingly.

**Comment by ric96** [comment]
@Mani-Sadhasivam I think it would be better to point to upstream examples

**Comment by Mani-Sadhasivam** [comment]
@ric96 Any update on this issue?

**Comment by ric96** [comment]
Is the issue only with pyupm_i2clcd being renamed to pyupm_lcd ? If so we should just do that in the doc. The example are specific to sensors mezzanine and redirecting to the upstream example wouldn't make sense.

**Comment by Mani-Sadhasivam** [comment]
@ric96 Please spare some time to test the Mezzanine examples we provide.

**Comment by Mani-Sadhasivam** [comment]
@ric96 Any update on this issue?
