### ISSUE TITLE
Broken links stopping website changes from going ahead.

### ISSUE THREAD

**Issue by kylekirkby** [96boards/documentation#580]
/documentation/consumer/hikey/hikey620/downloads/debian.md.html:
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest/linaro-stretch-developer-hikey-*.sd.gz [1]
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest [1]
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest/boot-linaro-stretch-developer-hikey-*.img.gz [1]
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest/rootfs-linaro-stretch-developer-hikey-*.img.gz [1]
/documentation/consumer/hikey/hikey960/downloads/Debian.md.html:
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest/linaro-stretch-developer-hikey-*.sd.gz [1]
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest [1]
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest/boot-linaro-stretch-developer-hikey-*.img.gz [1]
   http://snapshots.linaro.org/96boards/hikey/linaro/debian/latest/rootfs-linaro-stretch-developer-hikey-*.img.gz [1]

Relates to https://github.com/96boards/documentation/issues/579

Can we get these updated asap ?

Many thanks,

Kyle

**Comment by ric96** [comment]
The snapshots got deleted since they timed out, the best immediate workaround is to remove the links for now.
sent an email to @fboudra to discuss a possible solution.

**Comment by ric96** [comment]
Was fixed automatically after new builds were uploaded.
