### ISSUE TITLE
SoC_bubblegum96.pdf is lacking chapter information

### ISSUE THREAD

**Issue by afaerber** [96boards/documentation#59]
The Actions Semi S500 manual PDF v1.5 dated 2015-11-30, as available through LeMaker, has a chapter structure so that one can jump directly to certain peripherals in a suitable PDF reader. The S900 manual v1.0 dated 2015-10-28 in this repository here is lacking such metadata and only shows page previews, making it rather hard to navigate.

Is there a chance the SoC_bubblegum96.pdf manual can be updated please?

No manuals are publicly available through actions-semi.com.

**Comment by sdrobertw** [comment]
@afaerber  These documents are not made by Linaro/96Boards. I will do my best to find someone who can help you.

@blimjoe Are you able to shed some light on this issue?

**Comment by afaerber** [comment]
@sdrobertw Sure, it's got the Actions logo and copyright on it. The commit adding this file had you as author, so hopefully you on the 96Boards side can trace where it originated from. :)

**Comment by ProfFan** [comment]
My recent experiences with UCRobotics is terrible. I tried to contact them by email and got no response. I then turned to their sales on Taobao, which promised me that their engineer will respond. Two months passed and still zero response. I am giving up on this board.

**Comment by sdrobertw** [comment]
I will continue to reach out for a resolution on this issue, though it will depend on external commitment to fix.

I am going to leave the issue open for a while longer. If I am unable to find a way to get this document updated, I will have to close.

Please stay tuned.

**Comment by sdrobertw** [comment]
@blimjoe

**Comment by k3u97** [comment]
I'm sorry that you can't get the support quickly. For Bubblegum-96, it was made by uCRobtics, use S900 from Action-Semi, about for data sheet, it's better to ask for help from SoC vendor. I'm glad to bridge the connection for you in China.

**Comment by sdrobertw** [comment]
Thank you, @k3u97 . I have to agree. I tried tagging @blimjoe to see if he could add more information.

I will do my best to monitor and make improvements to the Bubblegum-96 docs section. 

May we close this issue?

**Comment by sdrobertw** [comment]
@k3u97 @blimjoe 

This issue will be closed by EoW due to inactivity. If you are still experiencing a problem, please open a new issue.

Thanks!
