### ISSUE TITLE
DB410C: Does using USB flashing tools really require a debug UART?

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#603]
Currently the section for board recovery using qdl (Connecting the board in USB flashing mode (aka EDL mode) instructs the users to connect a debug UART.

Is this really required? I cannot see anywhere that a command is sent via the UART; it only seems to be used to provide the user with a "warm fuzzy feeling" when the board changes between the various modes. Can't the same feeling be provided by watching for USB device enumation using `journalctl -fk` (or `dmesg -w` for users with old distros)?

URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard410c/installation/board-recovery.md.html

**Comment by Mani-Sadhasivam** [comment]
@daniel-thompson Can we just add `(optional)` to these steps?

**Comment by daniel-thompson** [comment]
That would be the minimum required, yes.

However currently the documentation is very unclear whether the "Update Backup Header with CRC of Backup Header." messages appears on the serial console or on the qdl stdout so we do need to be careful about which parts of the instructions get marked optional.

**Comment by Mani-Sadhasivam** [comment]
Will update the doc this week!

**Comment by Mani-Sadhasivam** [comment]
This one slipped through cracks... Will close this week
