### ISSUE TITLE
Ultra96-PYNQ is not listed as a third-party OS

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#608]
Avnet/Xilinx are releasing additional OSs for ultra96. One example, which came up on the forums, is:
https://github.com/Avnet/Ultra96-PYNQ

Can we ask Avnet to provide details for this page?

Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/ultra96/downloads/

**Comment by ric96** [comment]
Its in PR: https://github.com/96boards/documentation/pull/606
