### ISSUE TITLE
Image links in wiki page Dragonboard-410c-Installation-Guide-for-Linux-and-Android were broken

### ISSUE THREAD

**Issue by crvv** [96boards/documentation#62]
There are two broken images in page https://github.com/96boards/documentation/wiki/Dragonboard-410c-Installation-Guide-for-Linux-and-Android

https://github.com/96boards/documentation/raw/master/ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Wiki/image00.jpg
and
https://github.com/96boards/documentation/raw/master/ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Wiki/image01.jpg

The link should be updated to `ConsumerEdition/DragonBoard-410c/AdditionalDocs/Images/Images_Wiki/imageXX.jpg`

Please fix them, thanks.

**Comment by sdrobertw** [comment]
Hell @crvv - Thank you for the observation.

To be honest, this entire page (Set of instructions) should probably be forwarded to the new DB410c landing page. Most, if not all information can now be found in the subdirectories here:

https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/README.md

**Comment by sdrobertw** [comment]
I will run down the entire page to see if there is any additional information that should be salvaged. Otherwise, you can expect this page to be forwarded to the new landing page provided in the above comment.

Thanks again!

**Comment by sdrobertw** [comment]
Can I close this issue?

**Comment by crvv** [comment]
OK, I understood.

Maybe the wiki page should be deleted.

The issue can be closed.

**Comment by sdrobertw** [comment]
Thanks! I will extract any missing information and forward the page.
