### ISSUE TITLE
Problem with _documentation/consumer/sophon-edge/README.md

### ISSUE THREAD

**Issue by ASerbinski** [96boards/documentation#635]
A visual overview of the board shows that it doesn't come even close to meeting 96boards CE minimum functionality as per https://www.96boards.org/documentation/Specifications/96Boards-CE-Specification.pdf

-- Instead of OTG or C port near center of board, the two host ports are pushed into the center, and it uses a 3.0 A port *as* OTG. It clearly should have a C port in the standard location instead.
-- Does not have any display output capability at all.
-- Does not have high speed connector.
-- Component maximum height limit of 6.5mm appears to be exceeded by ethernet port.

I'm not suggesting that the board be removed, but it should be prominently noted that the board is non-compliant, and it should specify details of its non-compliance. In particular, the majority of mezzanine boards (even those which are low speed ONLY) will be incompatible with this board due to interference with the ethernet port.

**Comment by HEGALLIS** [comment]
Agreed with Adam - we should document clearly why this board is introduced under waiver because we believe it will address the gap among multiple technology group.

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Any update on this issue?

**Comment by sdrobertw** [comment]
Note regarding waivers has been added to the getting started section of the documentation set. 

Another note will be added to the web page shortly.

https://github.com/96boards/documentation/tree/master/consumer/sophon-edge/getting-started

**Comment by sdrobertw** [comment]
PRs for both Docs and Website should serve as temporary fixes to this issue as we find a better way to accent these compliance issues through a parametric search on the website. Currently on the 96Boards roadmap.

https://github.com/96boards/website/pull/1116
https://github.com/96boards/documentation/pull/848
