### ISSUE TITLE
No "edit me on github" links in the rendered documentation.

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#67]
As I write http://www.96boards.org/documentation/IoTEdition/Carbon/Building/LinuxBuild/BuildShell.md/ is completely broken! I'm about to fix it... and I'm annoyed that I have to manually convert the link to take me to github.

These pages should embed a link somewhere to take interested parties to the github markdown editor... From a UI PoV I'm "expecting" a corner label an the top similar to the "Fork me on github" labels but encouraging editing instead (in fact it could *be* a Fork me on github label but point to the underlying markdown file allowing the github interface to offer the editing features).

Anyhow, as a *user* I'm annoyed at seeing my time wasted on something that should be automated ;-)

**Comment by sdrobertw** [comment]
@daniel-thompson 

This is something that @shovanuk has been working on. I will ping him to make sure we keep this on the list. I think it is urgent to have these "Edit on Github" links available at the bottom of all paged that are rendered up.

Thanks!

**Comment by shovanuk** [comment]
@daniel-thompson http://www.96boards.org/documentation/IoTEdition/Carbon/Building/LinuxBuild/BuildShell.md/ works for me. The links within the pages open for me, can you point me to the right place?

Thanks

**Comment by daniel-thompson** [comment]
Hi Shovan

This bug is not about broken links. It is about the pain I endured when I fixed them.

Basically IMHO *every* generated page should contain a link back to the github source material encouraging the reader to "Edit me on github" if they find any problems.

I'm well connected to 96Boards so I knew (more or less by osmosis) that if I went grubbing about on some random github project I would be able to fix the links and send a PR. However most people (even within Linaro) don't know this. We should help them by providing links from each and every page.

The ideal UI from my point of view would be to copy the visual style of [github ribbons](https://github.com/blog/273-github-ribbons). For http://www.96boards.org/documentation/IoTEdition/Carbon/Building/LinuxBuild/BuildShell.md/ 
 the ribbon should link to https://github.com/96boards/documentation/edit/master/IoTEdition/Carbon/Building/LinuxBuild/BuildShell.md .

**Comment by sdrobertw** [comment]
@shovanuk 

We have talked about this in the past. There needs to be an "Edit me on Github" link at the bottom of each GitHub rendered page on the website... I could add this to the doc/.md file it self but when it would seem misplaced for those who only use GitHub and do not use the site.

Does this make sense?

**Comment by idlethread** [comment]
Misplaced as in extraneous? If so, it should be OK as long as the behaviour
is consistent - clicking takes you to the editor on github. Perhaps you can
convert one page to show what you don't like?

**Comment by sdrobertw** [comment]
@kylekirkby @shovanuk 

Any update on this?

**Comment by kylekirkby** [comment]
We have a project for 96boards Static Site here - https://projects.linaro.org/browse/MAR-221. This is one of the issues that are on that list. I will make sure this gets done first out of all feature requests/ bug fixes. 

Thanks

**Comment by sdrobertw** [comment]
Thanks, @kylekirkby 

Once it rolls out, we can close this issue.

**Comment by sdrobertw** [comment]
This has been addressed. Most pages on 96Boards.org website now have "Edit me on GitHub" options with links to the appropriate GitHub page for editing. 

Great work @shovanuk and @kylekirkby , thanks for doing this!

Closing issue.
