### ISSUE TITLE
Problem with _documentation/consumer/rock/rock960/hardware-docs/hardware-user-manual.md

### ISSUE THREAD

**Issue by alleynb333** [96boards/documentation#671]
Issue with the High Speed pinout table:
URL:  https://www.96boards.org/documentation/consumer/rock/rock960/hardware-docs/hardware-user-manual.md.html

36 | I2C3_SDA | I2C7_SCL
-- | -- | --

**Comment by Mani-Sadhasivam** [comment]
Fixed in #669
