### ISSUE TITLE
problem with building kernel

### ISSUE THREAD

**Issue by FireBirda** [96boards/documentation#672]
hi,
i'm working on Ubuntu 16.04 based on intel x86.

after comiling the kernel i cant find the Image file on the folder.
arch/arm64/boot/

what i'm missing?

thank you very much

omer.

**Comment by sdrobertw** [comment]
@FireBirda Which 96Boards are you working with?

Is there a guide within this repo that you are following?

**Comment by Mani-Sadhasivam** [comment]
@FireBirda This kind of questions would be better asked in 96Boards forum under relevant board section.
http://discuss.96boards.org
