### ISSUE TITLE
Problem with _documentation/mezzanine/mipiadapter/guides/README.md

### ISSUE THREAD

**Issue by Abrahamon** [96boards/documentation#675]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/mezzanine/mipiadapter/guides/

Hi! There are no guides in the link

**Comment by sdrobertw** [comment]
@Abrahamon 

The 96Boards Mezzanine guides sections are open for community contributions. Our team will continue to write guides over time for all of our partners products. We will have at least one guide for every 96Boards mezzanine available within Q1 of 2019.

If you are working with this mezzanine, please feel free to fork the documentation repo and submit your guides to help our community.

Please let us know if you have any questions.

@ric96 and @K1504296 are leading this effort.
