### ISSUE TITLE
Armbian

### ISSUE THREAD

**Issue by ritzeng** [96boards/documentation#678]
Armbian Linux is also supported? 
I use Armbian for other Oranhepi boards.

Best regards 
Frank
ritz@ritzeng.com

**Comment by Mani-Sadhasivam** [comment]
Hi @ritzeng,

Which board you are referring to?

**Comment by ritzeng** [comment]
Hello,

I’m sorry, I raised the question for the orange i96. I thought that it was placed at the right association. 

However, 
I thank you for a reply, 96boards is a very informative site. 

Best regards
Frank H. Ritz

Ritz Engineering GmbH, Buchzelgstrasse 47, CH- 8053 Zürich |  ritzeng.com  |  UID CHE-113.545.574
--
Mobile, Facetime, iMessage / SMS, WhatsApp, Telegram: +41762099720 | VOIP / SIP: +41445002542
--
www.ritzeng.ch  |  methoden.ch  |  intrinsics.ch | iotangle.ch | bit-chain.ch | genergy.ch | earsandeyes.ch
--
XING,LinkedIn,Facebook,Google,Slideshare,Reddit,Youtube | Twitter:@ritzeng | webcal://goo.gl/u7vkS
--

**Comment by sdrobertw** [comment]
@ritzeng thank you for the kind words! We are always making improvements to the site and our documentation :-)

Maybe someone else in this thread might now more, I have never used Armbian Linux with the 96Boards Orange Pi (not yet ;-) 

Please let us know if you end up testing this, this way we can add it as an option in one of our 3rd party sections.

Kind Regards.

**Comment by ric96** [comment]
@ritzeng 
this issue section only handles documentation related issue like wrong documentation, typos etc.
I'd suggest heading over to our forums and posting under the i96 subcategory: https://discuss.96boards.org/c/products/orangepi-i96

or better yet, on the armbian forums: https://forum.armbian.com/
