### ISSUE TITLE
Problem with _documentation/consumer/dragonboard/dragonboard820c/guides/aosp.md

### ISSUE THREAD

**Issue by marcelommcouto** [96boards/documentation#686]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard820c/guides/aosp/

You can correct:
1. In "Flashing the board", we have Dragonboard 820c not Dragonboard 410c

**Comment by Mani-Sadhasivam** [comment]
@marcelommcouto Thanks for pointing out the issue! @ric96 We might need to either add a pointer to fastboot page for rewrite the entire `Flashing the board` section.

**Comment by ric96** [comment]
will be combining under a single guide EoW
