### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by codehelp** [96boards/documentation#70]
The link to latest UEFI is wrong
Latest UEFI snapshot builds are published here. Download the following files:
leads to an empty directory.
http://builds.96boards.org/snapshots/hikey/linaro/uefi-openplatformpkg/latest/
?

Now skip to the Flash binaries to eMMC section. leads to a non-existent ID
https://github.com/96boards/documentation/wiki/HiKeyUEFI#flash-emmc
should be
https://github.com/96boards/documentation/wiki/HiKeyUEFI#flash-binaries-to-emmc-

There is no mention of how to tell whether to use 4G or 8G ptables.

There is also no mention of downloading  boot-fat.uefi.img and no link to it.

**Comment by sdrobertw** [comment]
@codehelp 

This is a document located in the 96Boards/documentation WIKI.. I am currently working on getting all of the wiki pages checked and transitioned over to the new docs repo format though this is taking a bit.

Have you taken a look at the instructions located in the Linaro/documentation repo?

https://github.com/Linaro/documentation/blob/master/Reference-Platform/Platforms/Consumer/PreviousReleases/RPB_16.06/ConsumerEdition/HiKey/README.md

Maybe this can tide you over until I am able to test and move this document to a better place?

**Comment by shovanuk** [comment]
@sdrobertw Couple more dead links on this page 
https://github.com/96boards/documentation/blob/master/ConsumerEdition/DragonBoard-410c/Downloads/OpenEmbedded.md

**Comment by sdrobertw** [comment]
@shovanuk nothing broken on my end on that page.

**Comment by shovanuk** [comment]
Seems to work now :)
