### ISSUE TITLE
Problem with _documentation/consumer/rock/downloads/debian.md

### ISSUE THREAD

**Issue by blazini36** [96boards/documentation#704]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/rock/downloads/debian.md.html

Rock960 "C" Debian Rootfs.img link is broken

**Comment by hipboi** [comment]
download link fixed now.

**Comment by ric96** [comment]
Closing since link fixed
