### ISSUE TITLE
when will updates rock960c camera setup guide?

### ISSUE THREAD

**Issue by aciddust** [96boards/documentation#712]
https://github.com/96boards/documentation/blob/master/consumer/rock/rock960c/guides/camera-setup.md
> documentation/consumer/rock/rock960c/guides/camera-setup.md.html

how to use camera on rock960c??

**Comment by Mani-Sadhasivam** [comment]
Hi @aciddust,

CSI on both Rock960 and Rock960c is almost same (haven't tested yet). So the instructions for Rock960 should work well too. But, I will test the CSI interface and update the guide ASAP.

**Comment by Mani-Sadhasivam** [comment]
@vamrs Will you be able to take care of this one?

**Comment by hipboi** [comment]
we will update it.
