### ISSUE TITLE
Link fixing

### ISSUE THREAD

**Issue by LeoPersike** [96boards/documentation#717]
Hi,
First of all, thank you very much for sharing your work and writing this nice tutorial, it works like a charm.

I would just like to mention that some links are not available or changed, so here are the updated links:

**Python relative links script:** https://raw.githubusercontent.com/Kukkimonsuta/rpi-buildqt/master/scripts/utils/sysroot-relativelinks.py

**GCC:** https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz

**QT5 super module:** https://github.com/qt/qt5

That's it :)
Thanks again for your awesome work.

BR,
Leonardo.

**Comment by ric96** [comment]
@LeoPersike Can you link to the tutorial page as well?

**Comment by LeoPersike** [comment]
Hi Ric,
Sorry, my fault. I was referring to this md:

https://github.com/96boards/documentation/blob/master/consumer/dragonboard/dragonboard410c/guides/DragonBoard-Qt-Setup.md

:)
