### ISSUE TITLE
consumer: db410c: Link to Win10 install instructions is broken

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#719]
> Please enter some details about the bug/issue so we can promptly resolve it. 
> URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard410c/downloads/

As subject. I'm afraid I do not know where Microsoft has moved the page to.

**Comment by sdrobertw** [comment]
Oh shoot...

I found this: 

- Device Setup: https://docs.microsoft.com/en-us/windows/iot-core/tutorials/quickstarter/devicesetup#using-the-iot-dashboard-dragonboard-410c
- Download: https://www.microsoft.com/en-us/download/details.aspx?id=55027

@ric96 would you mind taking care of this update?
