### ISSUE TITLE
fastboot <wating device>

### ISSUE THREAD

**Issue by wolfschus** [96boards/documentation#72]
HiKey620, Android, Ubuntu 16.04.02 

when i flash with` ./flash-all.sh /dev/ttyUSB0 [4g]`
the output:

```
+----------------------+
 Serial:  /dev/ttyUSB0
 Image1:  l-loader.bin
 Image2:  
+----------------------+

Sending l-loader.bin ...
Done

```
and nothing else. 

syslog after connect usb again:
---8<-----------------------------------------------------
```
May  8 14:59:13 depc232 kernel: [29562.595779] usb 8-2: new full-speed USB device number 34 using xhci_hcd
May  8 14:59:14 depc232 kernel: [29562.741816] usb 8-2: New USB device found, idVendor=12d1, idProduct=3609
May  8 14:59:14 depc232 kernel: [29562.741830] usb 8-2: New USB device strings: Mfr=1, Product=4, SerialNumber=0
May  8 14:59:14 depc232 kernel: [29562.741836] usb 8-2: Product: ㄰㌲㔴㜶㤸
May  8 14:59:14 depc232 kernel: [29562.741840] usb 8-2: Manufacturer: 䕇䕎䥎
May  8 14:59:14 depc232 kernel: [29562.743962] option 8-2:1.0: GSM modem (1-port) converter detected
May  8 14:59:14 depc232 kernel: [29562.744183] usb 8-2: GSM modem (1-port) converter now attached to ttyUSB0
May  8 14:59:14 depc232 mtp-probe: checking bus 8, device 34: "/sys/devices/pci0000:00/0000:00:10.1/usb8/8-2"
May  8 14:59:14 depc232 mtp-probe: bus: 8, device: 34 was not an MTP device
May  8 14:59:18 depc232 /usr/lib/snapd/snapd[958]: daemon.go:176: DEBUG: uid=1000;@ GET /v2/snaps 65.615µs 200
```

---8<-----------------------------------------------------

when i type `sudo fastboot devices -l` no devices are shown

when i type `sudo fastboot flash ptable ptable-linux-4g.img` it shown `< waiting for device >`

**Comment by vchong** [comment]
Can you try flashing the images manually to see if it works? Guide is here: https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/LinuxFastboot.md

**Comment by wolfschus** [comment]
I start a recovery:
https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/BoardRecovery.md
`sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin`
is done.

when i start `sudo fastboot flash ptable ptable-linux-8g.img`, i get `< waiting for device >`

In the syslog i got this:
```
May  9 07:23:42 depc232 ModemManager[902]: <info>  Creating modem with plugin 'Huawei' and '1' ports
May  9 07:23:42 depc232 ModemManager[902]: <warn>  Could not grab port (tty/ttyUSB0): 'Cannot add port 'tty/ttyUSB0', unhandled serial type'
May  9 07:23:42 depc232 ModemManager[902]: <warn>  Couldn't create modem for device at '/sys/devices/pci0000:00/0000:00:10.1/usb8/8-2': Failed to find primary AT port
```

**Comment by wolfschus** [comment]
Now I do:

`sudo apt-get remove modemmanager`

After Power-on the Board with linking 1-2 and 3-4 J601, I get in the syslog:

```
May  9 07:55:18 depc232 kernel: [ 4376.180909] usb 8-1: new full-speed USB device number 21 using xhci_hcd
May  9 07:55:19 depc232 kernel: [ 4376.326939] usb 8-1: New USB device found, idVendor=12d1, idProduct=3609
May  9 07:55:19 depc232 kernel: [ 4376.326946] usb 8-1: New USB device strings: Mfr=1, Product=4, SerialNumber=0
May  9 07:55:19 depc232 kernel: [ 4376.326957] usb 8-1: Product: ㄰㌲㔴㜶㤸
May  9 07:55:19 depc232 kernel: [ 4376.326960] usb 8-1: Manufacturer: 䕇䕎䥎
May  9 07:55:19 depc232 kernel: [ 4376.329097] option 8-1:1.0: GSM modem (1-port) converter detected
May  9 07:55:19 depc232 kernel: [ 4376.329278] usb 8-1: GSM modem (1-port) converter now attached to ttyUSB0
May  9 07:55:19 depc232 mtp-probe: checking bus 8, device 21: "/sys/devices/pci0000:00/0000:00:10.1/usb8/8-1"
May  9 07:55:19 depc232 mtp-probe: bus: 8, device: 21 was not an MTP device
```

The I start `sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin`
I get:
```
+----------------------+
(' Serial: ', '/dev/ttyUSB0')
(' Image1: ', 'l-loader.bin')
(' Image2: ', '')
+----------------------+

('Sending', 'l-loader.bin', '...')
Done

```
 and in the syslog:

```
May  9 07:55:27 depc232 kernel: [ 4384.655257] usb 8-1: USB disconnect, device number 21
May  9 07:55:27 depc232 kernel: [ 4384.657819] option1 ttyUSB0: GSM modem (1-port) converter now disconnected from ttyUSB0
May  9 07:55:27 depc232 kernel: [ 4384.657850] option 8-1:1.0: device disconnected
May  9 07:55:28 depc232 kernel: [ 4385.668616] usb 8-1: new full-speed USB device number 22 using xhci_hcd
May  9 07:55:28 depc232 kernel: [ 4385.814478] usb 8-1: New USB device found, idVendor=12d1, idProduct=3609
May  9 07:55:28 depc232 kernel: [ 4385.814484] usb 8-1: New USB device strings: Mfr=1, Product=4, SerialNumber=0
May  9 07:55:28 depc232 kernel: [ 4385.814487] usb 8-1: Product: ㄰㌲㔴㜶㤸
May  9 07:55:28 depc232 kernel: [ 4385.814489] usb 8-1: Manufacturer: 䕇䕎䥎
May  9 07:55:28 depc232 mtp-probe: checking bus 8, device 22: "/sys/devices/pci0000:00/0000:00:10.1/usb8/8-1"
May  9 07:55:28 depc232 kernel: [ 4385.816636] option 8-1:1.0: GSM modem (1-port) converter detected
May  9 07:55:28 depc232 kernel: [ 4385.816789] usb 8-1: GSM modem (1-port) converter now attached to ttyUSB0
May  9 07:55:28 depc232 mtp-probe: bus: 8, device: 22 was not an MTP device
```

Then I tried: `sudo fastboot flash ptable ptable-linux-8g.img`
I get: 
`< waiting for device >`

**Comment by vchong** [comment]
Do you have access to the serial console (uart)? If so, can you please post the corresponding console output when you run commands on your pc?

Just to rule things out, please remove all other cables (mouse, keyboard) and SD card from the board. Also make sure you run hisi-idt within 90 seconds of powering up the board.

Can you also try connecting 1-2 and 5-6 on J601, boot up the board and on your pc, run `sudo fastboot devices` to see if anything comes up?

Finally, since you'd mentioned using the `ptable-linux-4g.img` file previously, please make sure you use `ptable-linux-8g.img` since that's the right one for your board (Lemaker).

**Comment by wolfschus** [comment]
1. I  sniffed the /dev/ttyUSB0 Device while I do the command `sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin`

read:
```
AA AA AA AA AA AA AA AA AA AA AA               	...........
AA AA AA                                       	...
AA                                             	.
AA                                             	.
AA AA AA AA AA AA AA                           	.......
AA                                             	.
AA                                             	.
AA                                             	.
AA                                             	.
AA                                             	.
AA                                             	.
AA                                             	.
AA AA AA AA AA AA AA                           	.......
AA                                             	.
```
write:
Nothing ???

**Comment by wolfschus** [comment]
2. I do it so, no change

3. `sudo fastboot devices` -> Nothing

4. I use the 8g-img, but fastboot don't work because it cannot find the device

**Comment by vchong** [comment]
Are you using python 3? If so, maybe try with python 2.7. For details, refer to Problems with Python Downloader section in https://github.com/96boards/documentation/wiki/LatestSnapshots. Also want to make sure you're using an actual linux machine and not a virtual one hosted by windows/osx?

**Comment by wolfschus** [comment]
I am using python 2.7.
I am using Ubuntu 16.04.02 LTE on a Hardwaremachine.
Is it possible, that the Board is broken?

**Comment by vchong** [comment]
Possibly. Can't really tell for sure. :( It would be nice if you can access the serial console to see if anything else is going on. Maybe try a different microusb-usb cable and pc and even power supply (if available)? Or try to install new images using the SD card - https://github.com/Linaro/documentation/blob/master/Reference-Platform/Releases/RPB_16.06/ConsumerEdition/HiKey/InstallDebianRPB.md#sd-card-method.

Also checkout some related threads on the 96boards forum:
https://discuss.96boards.org/t/fastboot-fails-during-hikey-board-recovery-process/1122/8
https://discuss.96boards.org/t/hikey-recovery-fails-fastboot-issue/1711

**Comment by wolfschus** [comment]
ok, I will test it. I get yesterday also a new HiKey960-Board. I will test it with this today.

Thanx for your great support :1st_place_medal:

**Comment by wolfschus** [comment]
No Problems with the new Board. I think, the old board had a defect.
