### ISSUE TITLE
Problem with _documentation/consumer/dragonboard/dragonboard410c/installation/mac-sd.md

### ISSUE THREAD

**Issue by jbastosneto** [96boards/documentation#757]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard410c/installation/mac-sd.md.html

After following this guide I wan't able to get on step 9 GUI to install the OS on eMMC.

I followed step 8, but the board booted to the ubuntu core configuration and neve asked to install the image on the eMMC.

**Comment by sdrobertw** [comment]
@jbastosneto could you please visit the 96Boards forum (DragonBoard 410c section:

https://discuss.96boards.org/c/products/dragonboard410c

If you do not find the solution to your issue, please post a new thread and share it in our Discord channel: https://discord.gg/x5uMn5d

Issue tracking here has more to do with issues regarding the documentation it self, not issues with execution in the documentation. 

You will get more attention and trouble shooting help in our forum.

Thanks!
