### ISSUE TITLE
Missing mechanical drawings for i96

### ISSUE THREAD

**Issue by knivd** [96boards/documentation#758]
I have not been able to find any drawing that relates to the actual mechanical dimensions of the i96 board. Is there any available?

**Comment by Mani-Sadhasivam** [comment]
@knivd Will this help?
https://github.com/96boards/documentation/blob/master/iot/bpi96/hardware-docs/files/bpi96-assembly-top.pdf
https://github.com/96boards/documentation/blob/master/iot/bpi96/hardware-docs/files/bpi96-assembly-bottom.pdf

**Comment by knivd** [comment]
Thank you but these files don’t help at all. Where are the dimensions? Without dimensions it is not possible to create a model of the board in order to include it is a bigger system

**Comment by Mani-Sadhasivam** [comment]
@knivd Dimensions should be same as mentioned in the IoT edition specification.
https://linaro.co/ie-specification

**Comment by knivd** [comment]
That file helped. Thank you.
