### ISSUE TITLE
hikey970: hoperun website update leaves dead links

### ISSUE THREAD

**Issue by eoghankennedy** [96boards/documentation#759]
Download link seems to be broken - Is there an alternative location?

 
URL:  https://www.96boards.org/documentation/consumer/hikey/hikey970/downloads/aosp.md.html

**Comment by vchatterji** [comment]
The URL is:
http://hihope.org/hihope/downLoadCenter/index?productName=0&page=1&pageSize=10

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw @ric96 Please update all hoperun links in our doc repo.
