### ISSUE TITLE
poplar - missing info what mfg:pn is used for j14, j15

### ISSUE THREAD

**Issue by cz172638** [96boards/documentation#76]
i can't identify which manufacturer and which partnumber is used for non-standard jtag and uart connectors:<br/>
 j14 (jtag - SDW12501A_8A_HW in schematics) and <br/>
 j15 - (uart - SDW12501_4A_HW).<br/>
bill of material for poplar whould be nice, or list of appropriate headers for all connectors used in poplar.

**Comment by sdrobertw** [comment]
@alexelder @daniel-thompson @ric96 @vchong 

Any help on this one?

**Comment by daniel-thompson** [comment]
This thread is a cross post from the forum:
https://discuss.96boards.org/t/identity-of-sdw12501-connectors/1965/3

Appears to have been answered there.
