### ISSUE TITLE
db845c: Permission denied when downloading SDK

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#764]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard845c/build/le-os.md.html

As https://discuss.96boards.org/t/robotics-dragonboard-845c/7708/3 , the "Download SDK" link results in a permission denied error from the Thundercomm server.

**Comment by sdrobertw** [comment]
@daniel-thompson 

I have sent out an email to try and get this resolved asap. You are included in said email.

Thanks!

**Comment by daniel-thompson** [comment]
It looks like this affects more than one link on the Thundercomm site. See also:
https://www.96boards.org/documentation/consumer/dragonboard/dragonboard845c/downloads/

**Comment by sdrobertw** [comment]
SDK will remain broken. We might get this download from Thundercomm in the coming month. For now, we will remove the LE OS build guide from the DB845c documentation set. 

Fixed download link for pre-build LE OS.

https://github.com/96boards/documentation/pull/765
