### ISSUE TITLE
Build instructions are not sufficient due to many missing files

### ISSUE THREAD

**Issue by sherrellbc** [96boards/documentation#77]
Attempting to build from source using the steps as defined [here](https://github.com/96boards/documentation/wiki/HiKeyUEFI#source-code) is no longer sufficient. I have not quite made it so far to test anything other than building EDK. Using the recommended build command:

`../uefi-tools/uefi-build.sh -c ../LinaroPkg/platforms.config -b RELEASE -a ../arm-trusted-firmware -s ../optee_os hikey`

The first error is a simple pedantic one:
```
g++  -I Pccts/h -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/   -c -o VfrUtilityLib.o VfrUtilityLib.cpp
VfrUtilityLib.cpp: In member function ‘CHAR8* CVfrStringDB::GetVarStoreNameFormStringId(EFI_STRING_ID)’:
VfrUtilityLib.cpp:3287:26: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (mStringFileName == '\0' ) {
                          ^~~~
make[2]: *** [<builtin>: VfrUtilityLib.o] Error 1

```

Changing this comparison to use `0` rather than the ASCII character `\0` seemed to fix the problem. However, immediately following this fix we're met with another error:

```
build.py...
 : error 000E: File/directory not found in workspace
        OpenPlatformPkg/Platforms/Hisilicon/HiKey/HiKey.dsc is not found in packages path:
        /home/user/hikey_board/build/inaro-edk2/.

- Failed -

```

The first problem is that this seems to be a submodule of the [96boards-hikey/edk2](https://github.com/96boards-hikey/edk2.git) git repo. Since these are not cloned by default, adding `--recursive` to the `git clone` string should do the trick. However, after cloning the submodule the HiKey.dsc file was still not present. I poked around a bit I found this file over in the [Linaro OpenPlatformPkg](https://git.linaro.org/uefi/OpenPlatformPkg.git/tree/Platforms/Hisilicon/HiKey) git repo. I then just cloned this repo over the (presumably older?) version included as a submodule.

```
cd linaro-edk2
https://git.linaro.org/uefi/OpenPlatformPkg.git/
```

Although this seemed to fix the problem above, the next problem is another missing file:

```
build.py...
/home/user/hikey_board/build/linaro-edk2/OpenPlatformPkg/Platforms/Hisilicon/HiKey/HiKey.dsc(44): error 000E: File/directory not found in workspace
        ArmPkg/Library/ArmLib/ArmBaseLib.inf is not found in packages path:
        /home/user/hikey_board/build/linaro-edk2/.

- Failed -
```

I also managed to find these files, but as part of the [Tianocore](https://github.com/tianocore/edk2/tree/master/ArmPkg/Library/ArmLib) git repo. Adding this file results in more missing files. I stopped after a few iterations.

It seems the provided steps may be outdated. Or maybe we need to use an older version of `uefi-tools`? Could you provide an updated build guide?

EDIT:
Upon closer review, it seems like my cross-compiler is not being properly picked up by the UEFI build script. However, the build problems are unrelated.

**Comment by vchong** [comment]
@sherrellbc That wiki is outdated. You can still follow it to install the custom toolchain, which is required. Then:

UEFI_TOOLS_GIT_URL=https://git.linaro.org/uefi/uefi-tools.git
UEFI_TOOLS_GIT_BRANCH=master
    EDK2_GIT_URL=https://github.com/96boards-hikey/edk2.git
    EDK2_GIT_VERSION="origin/hikey-aosp"
    ATF_GIT_URL=https://github.com/96boards-hikey/arm-trusted-firmware.git
    ATF_GIT_VERSION="origin/hikey"
    OPEN_PLATFORM_PKG_GIT_URL=https://github.com/96boards-hikey/OpenPlatformPkg.git
    OPEN_PLATFORM_PKG_GIT_BRANCH=hikey-aosp
OPTEE_OS_GIT_URL=https://github.com/OP-TEE/optee_os.git
OPTEE_GIT_VERSION=master

export AARCH64_TOOLCHAIN=GCC49

git clone -b $UEFI_TOOLS_GIT_BRANCH $UEFI_TOOLS_GIT_URL uefi-tools

git clone $EDK2_GIT_URL edk2
cd edk2
git checkout -b stable-baseline $EDK2_GIT_VERSION
cd ..

git clone -b $OPEN_PLATFORM_PKG_GIT_BRANCH $OPEN_PLATFORM_PKG_GIT_URL OpenPlatformPkg

cd edk2; rm -rf OpenPlatformPkg
ln -s ../OpenPlatformPkg
cd ..

git clone $ATF_GIT_URL arm-trusted-firmware
cd arm-trusted-firmware
git checkout -b stable-baseline $ATF_GIT_VERSION
cd ..

git clone $OPTEE_OS_GIT_URL optee_os
cd optee_os
git checkout -b stable-baseline $OPTEE_GIT_VERSION
cd ..

export EDK2_DIR=${WORKSPACE}/${BUILD_NUMBER}/edk2
export ATF_DIR=${WORKSPACE}/${BUILD_NUMBER}/arm-trusted-firmware
export OPTEE_OS_DIR=${WORKSPACE}/${BUILD_NUMBER}/optee_os
export UEFI_TOOLS_DIR=${WORKSPACE}/${BUILD_NUMBER}/uefi-tools

cd ${EDK2_DIR}
bash -x ${UEFI_TOOLS_DIR}/uefi-build.sh -T GCC49 -b RELEASE -a ${ATF_DIR} -s ${OPTEE_OS_DIR} hikey

**Comment by sherrellbc** [comment]
@vchong 
These updates seem to _almost_ work. I had to remove the `${WORKSPACE}` and `${BUILD_NUMBER}` references; I just replaced both with one `${PWD}`. 

The first compilation error I mentioned is still a problem (but manually fixable)
```

g++  -I Pccts/h -I .. -I ../Include/Common -I ../Include/ -I ../Include/IndustryStandard -I ../Common/ -I .. -I . -I ../Include/X64/   -c -o VfrUtilityLib.o VfrUtilityLib.cpp
VfrUtilityLib.cpp: In member function ‘CHAR8* CVfrStringDB::GetVarStoreNameFormStringId(EFI_STRING_ID)’:
VfrUtilityLib.cpp:3287:26: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
   if (mStringFileName == '\0' ) {
                          ^~~~
make[2]: *** [<builtin>: VfrUtilityLib.o] Error 1
```

The master branch of `l-loader` does not have a `debug.S`, so the final binary will not be generated. The following commands will fail:

```
arm-linux-gnueabihf-gcc -c -o debug.o debug.S
arm-linux-gnueabihf-ld -Bstatic -Tl-loader.lds -Ttext 0xf9800800 start.o debug.o -o loader
```

I just removed the debug.o dependency and the build properly finished. 

However, the [hikey](https://github.com/96boards-hikey/l-loader/tree/hikey) branch _does_ have this source file. Of course, debugging would be useful. Aside from the debug printing, `start.S` looked to be identical in both the `master` and `hikey` branches. I copied `debug.S`, `start.S`, and `serial_pl011.h` from `hikey` into `master` and the build went through. 

I tried to build _from_ the `hikey` branch but `gen_loader.py` will fail with:

```
Traceback (most recent call last):
  File "gen_loader.py", line 263, in <module>
    main(sys.argv[1:])
  File "gen_loader.py", line 258, in main
    loader.create_stage2(img_prm_ptable, img_sec_ptable, output_img)
UnboundLocalError: local variable 'img_sec_ptable' referenced before assignment
```
Taking a peek into this file shows that if [--img_prm_ptable](https://github.com/96boards-hikey/l-loader/blob/master/gen_loader.py#L244) is passed then `stage2` is set to 1. Then, since stage2=1, [this](https://github.com/96boards-hikey/l-loader/blob/master/gen_loader.py#L263) method is called with an uninitialized `img_sec_ptable`. I dumped the arguments to this python script and this does seem to be what is happening:

`['-o', 'l-loader.bin', '--img_loader=temp', '--img_bl1=bl1.bin']`

Also, there are confusingly two l-loader repos. One owned by [96boards-hikey](https://github.com/96boards-hikey/l-loader) and the other just by [96boards](https://github.com/96boards/l-loader). Your instructions use the former, so I assume that is the correct one?

**Comment by vchong** [comment]
> These updates seem to almost work. I had to remove the ${WORKSPACE} and ${BUILD_NUMBER} references; I just replaced both with one ${PWD}.

Ah sorry, copy paste error. I've updated the instructions.

Regarding l-loader, I understand your confusion, but I believe that the program is small enough that as long as you manage to get it to build, you can use any one of the methods that worked for you.

Actually (and hopefully this doesn't add to the confusion :s) I just remembered there's a 'newer' set of instructions here: https://github.com/Linaro/documentation/blob/master/Reference-Platform/Releases/RPB_16.06/ConsumerEdition/HiKey/BuildSourceBL.md, and for l-loader all that you need to do should just be to run `make`!

**Comment by sherrellbc** [comment]
@vchong Perfect. Thanks for the updates! I've a bit of trouble flashing the device (HiKey) properly, though. It seems the flasher is a bit unreliable. Once it failed, the second time completed properly by the filesystem was damaged, and then a third time it succeeded and I was able to boot (but still with a few `fsck`-related errors in the boot log). 

However, the build documentation works as expected. This issue can be closed as far as I'm concerned!

**Comment by vchong** [comment]
Are you flashing from what we call 'uefi' mode, i.e. jumpers 1-2 5-6 closed? For flashing the system/rootfs, flashing from 'recovery' mode, i.e. jumpers 1-2 3-4 closed seems to be much better. The only thing is you've to go through the trouble of running hisi-idt first, i.e.

$ sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin (again, remember ttyUSB* can change)
$ sudo fastboot flash ptable ptable-linux-8g.img (or 4g)
$ sudo fastboot flash fastboot fip.bin
$ sudo fastboot flash nvme nvme.img
$ sudo fastboot flash boot boot-fat.uefi.img (boot image file name can change based on build)
$ sudo fastboot flash system rootfs.img (this is not in the link below but you can do this from here as well)

re: https://github.com/96boards/documentation/blob/master/ConsumerEdition/HiKey/Installation/BoardRecovery.md

**Comment by sdrobertw** [comment]
@vchong , what is the status of this issue?

Can we label and/or close? Please :)

Thanks!
