### ISSUE TITLE
Problem with _documentation/consumer/hikey/hikey970/build/linux-kernel.md

### ISSUE THREAD

**Issue by LeoPersike** [96boards/documentation#779]
Hi, there is a problem to build the kernel from HiKey970.
https://www.96boards.org/documentation/consumer/hikey/hikey970/build/linux-kernel.md.html

Here's the output:

> [ 51% 5162/10028] build out/target/product/hikey9...cy_neverallows_intermediates/sepolicy_neverallows
> FAILED: out/target/product/hikey970/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows 
> /bin/bash -c "(rm -f out/target/product/hikey970/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows ) && (ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c 		30 -o out/target/product/hikey970/obj/ETC/sepolicy_neverallows_intermediates/sepolicy_neverallows out/target/product/hikey970/obj/ETC/sepolicy_neverallows_intermediates/policy.conf )"
> device/linaro/hikey/sepolicy/hostapd.te:4:ERROR 'unknown type hostapd' at token ';' on line 41810:
> typeattribute hostapd data_between_core_and_vendor_violators;
> \# hostapd no longer directly accesses /data outside /data/vendor.
> checkpolicy:  error(s) encountered while parsing configuration
> out/host/linux-x86/bin/checkpolicy:  loading policy configuration from out/target/product/hikey970/obj/ETC/sepolicy_neverallows_intermediates/policy.conf
> [ 51% 5165/10028] //external/boringssl:libssl clang++ src/ssl/custom_extensions.cc [linux_glibc]
> ninja: build stopped: subcommand failed.
> 13:46:36 ninja failed with: exit status 1
> 
> #### failed to build some targets (14:36 (mm:ss)) ####

Any fix for that? I saw this post:
https://discuss.96boards.org/t/aosp-build-failing-for-hikey970/6553/3
Should I remove the hostapd from the product packages? What is the implication of removing it?

**Comment by ric96** [comment]
This is a bug related to kernel source provided by the vendor and not Linaro. Please take a look at the discussion on our forums on the exact same topic: https://discuss.96boards.org/t/aosp-build-failing-for-hikey970/6553/3

Closing: not a doc repo related bug.
