### ISSUE TITLE
Missing mechanical drawings for HiKey970

### ISSUE THREAD

**Issue by nmoshrefi** [96boards/documentation#782]
Hello
Please let me know where I can find "Mechanical Details" or "CAD files" for HiKey970
we need to design a case for our project with Hikey970 and cannot find Hikey970 CAD file or Mechanical Details.

Best Regards
Nader

URL:  https://www.96boards.org/documentation/consumer/hikey/hikey970/

**Comment by sdrobertw** [comment]
@nmoshrefi the extent of hardware documents you will find for this board can be found here:

https://www.96boards.org/documentation/consumer/hikey/hikey970/hardware-docs/

Partners are not required to provide more than schematics and hardware user manual for 96Boards compliance. You might find some mechanical information in the Hardware User Manual.

I will be closing this issue for now. Please feel free to reopen if needed. Also, we recommend you join our 96Boards Discord Server: https://discord.gg/x5uMn5d

There you might find more support from the community and/or partners themselves.
