### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sdrobertw** [96boards/documentation#785]
Where can I get latest gcc toolchain ? I am trying to follow 

https://www.96boards.org/documentation/consumer/dragonboard/dragonboard410c/build/kernel.md.html looks like the link is broken

wget gives 404

PM oops looks like gcc-8 is now at ARM site.. I will take it from there..

FROM MISHRADK on IRC

**Comment by ric96** [comment]
Looks like the link got fixed.
I can run the wget command now.
Closing
