### ISSUE TITLE
fs_config_generator.py fsconfig: error: argument --all-partitions: expected one argument 

### ISSUE THREAD

**Issue by GensaGames** [96boards/documentation#787]
Hello, 

Following all the instructions from the doc. There is an issue, as mentioned in the name. From other threads, there is possible to resolve it with changes in : 

"""
_command = /bin/bash -c "build/make/tools/fs_config/fs_config_generator.py fsconfig --aid-header system/core/include/private/android_filesystem_config.h --capability-header bionic/libc/kernel/uapi/linux/capability.h --partition system --all-partitions '' --dirs --out_file out/target/product/hikey970/obj/ETC/fs_config_dirs_system_intermediates/fs_config_dirs_system /dev/null"_

_command = /bin/bash -c "build/make/tools/fs_config/fs_config_generator.py fsconfig --aid-header system/core/include/private/android_filesystem_config.h --capability-header bionic/libc/kernel/uapi/linux/capability.h --partition system --all-partitions '' --files --out_file out/target/product/hikey970/obj/ETC/fs_config_files_system_intermediates/fs_config_files_system /dev/null"_

"""

I'm sure there is right way to change script in build folder.
Any updates on this?

Thanks,

**Comment by Mani-Sadhasivam** [comment]
@GensaGames Is this document hosted by 96Boards?

**Comment by GensaGames** [comment]
I think it was hosted by Google. But docs for the building 96 boards.

**Comment by ric96** [comment]
Please bring such queries to our [Fourms](https://discuss.96boards.org/)
Closing: as bug is not related to the contents of this repo
