### ISSUE TITLE
Problem with _documentation/consumer/hikey/hikey960/downloads/aosp.md

### ISSUE THREAD

**Issue by sebamateja** [96boards/documentation#795]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/hikey/hikey960/downloads/aosp.md.html
Can't download or view factory image zip

**Comment by kylekirkby** [comment]
Hi @sebamateja,

Looks like this link needs updating please use the following:

https://snapshots.linaro.org/96boards/hikey960/linaro/aosp-master/latest/

Hope this helps!

BR,

Kyle

**Comment by ric96** [comment]
The is a factory image in the location. `hikey960-linaro-2019.07.31-factory-bad22762.zip`
