### ISSUE TITLE
On Camera Mezz Doc's are "Coming soon..."

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#803]
Please enter some details about the bug/issue so we can promptly resolve it.

This is the document I think we would refer this poster too: https://www.96boards.org/documentation/mezzanine/on-camera/guides

Unfortunately it is missing so I don't think we can offer any reply here.

URL:  https://www.96boards.org/documentation/mezzanine/on-camera/guides/

**Comment by sdrobertw** [comment]
Currently only docs we have for On-Camera Mezzanine can be found here: https://github.com/96boards/documentation/tree/master/mezzanine/on-camera

Until we are provided with sample boards, we are unable to create guides of our own. Thus, we will depend on the community of board owners to help with this. I will be closing this issue for now.
