### ISSUE TITLE
HIKEY960 Board is not going to fastboot

### ISSUE THREAD

**Issue by lokanadha27** [96boards/documentation#829]
After flashing ./hikey_idt -c config -p /dev/ttyUSB0
Device is not going to fastboot.
Even if I put the board in fastboot by turning on switch 1 and switch 3, the board is not going to fastboot. 
From UART adapter I got the following log:

 xloader chipid is: 0x36600110, start at 458ms.
Build Date: Sep 19 2017, 15:34:09
[clock_init] ++
hikey960 [hikey960_clk_init]
hi3660 [clk_setup]
[clock_init] --
storage type is UFS
ufs retry: 6 count v_tx:0 v_rx:0
ufs set v_tx:0 v_rx:0
Hikey960[5301] no need avs_init.
ddr ft:0xf20332a3,mode:1 target:4
UceLdOk
ch 0 gt_errfail, STATUS:0x00000060
ch 0 gdst_errfail, STATUS:0x00000040
ch 1 gt_errfail, STATUS:0x00000060
ch 1 gdst_errfail, STATUS:0x00000040
ch 2 gt_errfail, STATUS:0x00000060
ch 2 gdst_errfail, STATUS:0x00000040
ch 3 gt_errfail, STATUS:0x00000060
ch 3 gdst_errfail, STATUS:0x00000040
timeout
timeout
timeout
timeout
density: 0x0c0c0c0c,0x00000000,0x0c0c0c0c,0x00000000,0x0c0c0c0c,0x00000000,0x0c0c0c0c,0x00000000 
ddr info 0x00000306 
400M
685M
1067M
C1R,V0x0000002c e:66
C0R,V0x0000002c e:66
C1R,V0x0000002d e:66
C2R,V0x0000002c e:66
C3R,V0x0000002d e:113
C0R,V0x0000002d e:66
C1R,V0x0000002e e:66
C2R,V0x0000002d e:66
C3R,V0x0000002e e:66
C0R,V0x0000002e e:66
C1R,V0x0000002f e:65
C2R,V0x0000002e e:66
C3R,V0x0000002f e:66
C0R,V0x0000002f e:65
C1R,V0x00000030 e:65
C2R,V0x0000002f e:66
C3R,V0x00000030 e:65
1244M
1866M
C0R,V0x00000016 e:66
C0R,V0x00000017 e:66
C1R,V0x00000017 e:66
C2R,V0x00000017 e:66
iomcu_subsys_init
boot_c0 PROFILE 4

Normal boot up is also not happening. I'm getting the same error log.
Can someone please help me resolve this?

**Comment by sdrobertw** [comment]
@lokanadha27 this issue needs to be brought to our official 96Boards forum, there is an entire section dedicated to HiKey960. 

https://discuss.96boards.org/c/products/hikey960

I recommend first searching to see if anyone else is having the same issue. If not, please post your issue. Someone from out team, support, or the greater community might be able to help. You will have much further reach by using the forum.

This Issue area is more for bugs/comments/changes to docs.

Also, I would highly recommend joining our 96Boards Discord Server: https://discord.gg/x5uMn5d

You can interact with our team, partners and community in this server.

Hope this helps! I will be closing the issue for now in the hope you will re-post in the forums.
