### ISSUE TITLE
Problem with _documentation/consumer/dragonboard/dragonboard845c/installation/board-recovery.md

### ISSUE THREAD

**Issue by rbmistry** [96boards/documentation#833]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/dragonboard/dragonboard845c/installation/board-recovery.md.html

The instructions to put the device into EDL mode do not seem to work.
This is what worked on my test bench:

- Set the switch "DIP_SW" to "0 1 1 0 0 0" 
(Turn on SW2 on the dip switch to enable the USB2.0 debug port
Turn on SW3 on the Dip Switch to enable the auto power up on
USB-C cable connection)

- Power off the board and make sure the USB type-C cable is not plugged into the board

- Press button 18 (e.g. marked with F_DL), and

- Connect the USB3 Type C (5) between the Linux PC and the board

**Comment by sdrobertw** [comment]
@rbmistry when we have time to test this, we will narrow down this guide; however, until then, we have included your observations as an option during this board-recovery process. If users are not able to satisfy their needs with the previous guide, your option will follow. This fix can be found in the following PR:

https://github.com/96boards/documentation/pull/846
