### ISSUE TITLE
AOSP build for DragonBoard 410C is not working now

### ISSUE THREAD

**Issue by tonyho** [96boards/documentation#85]
I repo sync and build the AOSP, it failed for some dependence chaged. Below is how to fix them:
1. compositor
In external/drm_hwcompositor/Android.mk, Add following line to the LOCAL_C_INCLUDES:
	external/drm_gralloc \

This is caused by the drm_hwcompositor changes the drm to grm

2. Append the CFlags for libdrm
Add following to external/libdrm/Android.mk to fix the compile error, for the mix declaration and definition in libdrm code.
LOCAL_CFLAGS +=  -std=gnu99

**Comment by sdrobertw** [comment]
@ric96 @Mani-Sadhasivam 

any advice for this one?

**Comment by ric96** [comment]
This is a guide based on Rob Herring's work, https://github.com/robherring/generic_device
I think this issue was resolved, but if you are still facing it open up an issue in the above linked repo.
