### ISSUE TITLE
ultra96 v2 getting-started documentation is incorrect

### ISSUE THREAD

**Issue by anielsen001** [96boards/documentation#855]
I just received an ultra96 v2, which comes with a printed getting-started insert. The information on the insert conflicts with the website. The website info is incorrect. For example, the microSD card that came shipped with the kit is blank and the photos and description of the power button location do not match the board I received. 

The information on the insert appears to be correct and so far is working for me.

**Comment by sgermanserrano** [comment]
Solved in #865
