### ISSUE TITLE
Problem with _documentation/consumer/hikey/hikey960/downloads/aosp.md

### ISSUE THREAD

**Issue by waterdr0p** [96boards/documentation#859]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/consumer/hikey/hikey960/downloads/aosp.md.html

When I open https://snapshots.linaro.org/96boards/hikey960/linaro/aosp-master/latest/, then try to download something, this page is redirect to "You do not have permission to access this file." page.

**Comment by sgermanserrano** [comment]
This seems to be the same problem as #861 
Please use the build from this location: https://snapshots.linaro.org/96boards/hikey960/linaro/aosp-master/1013/

**Comment by sgermanserrano** [comment]
Closed in favour of #861
