### ISSUE TITLE
Problem with download links - _documentation/consumer/hikey/hikey960/downloads/aosp.md

### ISSUE THREAD

**Issue by jjustman** [96boards/documentation#861]
All of the download links for the following images listed at https://snapshots.linaro.org/96boards/hikey960/linaro/aosp-master/latest are reporting:

"You do not have permission to access this file."

![image](https://user-images.githubusercontent.com/8549609/68270233-82601380-0011-11ea-9bf9-3161df0f815d.png)

![image](https://user-images.githubusercontent.com/8549609/68270253-9146c600-0011-11ea-9fbd-77e8badad3e9.png)

**Comment by vishalbhoj** [comment]
The latest link is broken. Please use the build from this location: https://snapshots.linaro.org/96boards/hikey960/linaro/aosp-master/1013/

**Comment by sgermanserrano** [comment]
@vishalbhoj @kylekirkby who can fix the wrong link?

**Comment by sgermanserrano** [comment]
This looks fixed now
