### ISSUE TITLE
Broken link in Hikey Downloads: https://github.com/96boards/documentation/blob/aeec4afccf14ca47ac53ed9547dbbfb535ddfdd1/consumer/hikey/hikey620/downloads/debian.md

### ISSUE THREAD

**Issue by K1504296** [96boards/documentation#876]
Hi, there seems to be a broken link in the Hikey installation process.  

https://github.com/96boards/documentation/blob/aeec4afccf14ca47ac53ed9547dbbfb535ddfdd1/consumer/hikey/hikey620/downloads/debian.md

Both the ptable-linux-4g.img and the ptable-linux-8g.img forward to missing files in snapshots.linaro.org.

Page not found: /reference-platform/components/uefi-staging/latest/hikey/debug/ptable-linux-8g.img
Page not found: /reference-platform/components/uefi-staging/latest/hikey/debug/ptable-linux-4g.img

**Comment by K1504296** [comment]
The correct links may be here?

https://releases.linaro.org/96boards/reference-platform/debian/hikey/15.12/bootloader/

**Comment by kylekirkby** [comment]
Or here: http://releases.linaro.org/96boards/hikey/linaro/debian/latest/

**Comment by sgermanserrano** [comment]
@K1504296 did you manage to find the right image to use?

**Comment by K1504296** [comment]
@sgermanserrano I booted a Hikey recently and I believe that both worked. I'm just not sure if there's a preference for the instructions.

**Comment by sgermanserrano** [comment]
IMO the one from latest might be better

**Comment by K1504296** [comment]
Okay, I'll post a PR

**Comment by sgermanserrano** [comment]
Fixed by #882
