### ISSUE TITLE
qdl connection timeout; payload too large ?

### ISSUE THREAD

**Issue by mh4nx7net** [96boards/documentation#887]
qdl: failed to read: Connection timed out
LOG: Host's payload to target size is too large
![grimshoot-slurp-2020-04-14-18-20-50](https://user-images.githubusercontent.com/33443311/79219601-c5ee6180-7e7c-11ea-9b6f-1e11fcefc6c9.png)

**Comment by ric96** [comment]
this doesn't look like a documentation issue. please post this on our forums. https://discuss.96boards.org
