### ISSUE TITLE
All OrangePi i96 software links are broken (404)

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#898]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.96boards.org/documentation/iot/orangepi-i96/downloads/

Every link on this page is broken (yields a 404 error)

**Comment by Thore-Krug** [comment]
#906 I created a Pull request regarding these Links.

**Comment by Thore-Krug** [comment]
The PR was merged thus the links are fixed and  this issue can be closed.
