### ISSUE TITLE
Dragonboard 845c installation steps invisible

### ISSUE THREAD

**Issue by eswierk** [96boards/documentation#920]
Some of the installation steps are rendered as white text on white background, making them invisible. As a workaround one can select the text to change the colors temporarily.

For example see Step 4: Flash Images at https://www.96boards.org/documentation/consumer/dragonboard/dragonboard845c/installation/le.md.html .

![dragonboard845c-installation-le-invisible](https://user-images.githubusercontent.com/355618/107969382-901a7d80-6f64-11eb-9a2f-7adbd07a5868.png)
![dragonboard845c-installation-le-invisible-selected](https://user-images.githubusercontent.com/355618/107969376-8d1f8d00-6f64-11eb-823e-023c111ad51c.png)

**Comment by sgermanserrano** [comment]
@eswierk Thanks for pointing that out. #921 should fix the problem

**Comment by sgermanserrano** [comment]
Fixed now
