### ISSUE TITLE
Relative links are not being exported correctly

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#93]
Just been talking to @lag-linaro .

Lee spotted a bunch of broken links in the 96Boards documentation and it turns out this is a bug in the way we are converting the markdown forest into HTML.

Specifically the HTML file for filename.md is placed into filename.md/index.html. This is a clever trick to allow direct links to .md filenames to work but breaks a number of links because ../ is not being prepended to all the relative links.

See http://www.96boards.org/documentation/ConsumerEdition/HiKey/Downloads/Debian.md/index.html for an example (the underlying link is ../Installation.md but this needs an extra ../ prepending for the link to work).

**Comment by shovanuk** [comment]
@daniel-thompson this issue is now fixed. Please open private window and try navigating from this page http://www.96boards.org/documentation/ConsumerEdition/HiKey/Downloads/

Thanks
Shovan
