### ISSUE TITLE
Problem with building OPTEE with benchmark

### ISSUE THREAD

**Issue by cti0ncep** [96boards/documentation#935]
Hello,

i modified common.mk and set CFG_TEE_BENCHMARK=y, but the build system stops with error:
**optee_benchmark_ext 1.0 Syncing from source dir**
ERROR:  does not exist
package/pkg-generic.mk:185: recipe for target '/optee/out-br/build/optee_benchmark_ext-1.0/.stamp_rsynced' failed
make[2]: *** [/optee/out-br/build/optee_benchmark_ext-1.0/.stamp_rsynced] Error 1
Makefile:23: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/optee/out-br'
common.mk:289: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

I checked the folder /optee/out-br/build/optee_benchmark_ext-1.0 is empty.
Also i tried to do this with: make CFG_TEE_BENCHMARK=y
The same error showed.
Any idea of the problem?

**Comment by vchong** [comment]
@cti0ncep Please repost this @ https://github.com/OP-TEE/build/issues/new.
