### ISSUE TITLE
Mezzanine Products URL

### ISSUE THREAD

**Issue by shovanuk** [96boards/documentation#94]
Hi Robert, 

Do you want to change the perma link of Mezzanine product? 

permalink: /documentation/MezzanineProducts/ <<-- Current
permalink: /documentation/mezzanine-docs/ <<-- Requested

Thanks
Shovan

**Comment by sdrobertw** [comment]
Yes

**Comment by sdrobertw** [comment]
I want the link to be mezzanine-docs I am trying to transition to all lower case in the most subtle way possible over the course of the next year >.<

**Comment by shovanuk** [comment]
Cool, 

Make sure you have old links in the redirect section

```
permalink: /documentation/mezzanine-docs/UARTSerial/
redirect_from: 
- /documentation/MezzanineProducts/UARTSerial/README.md/
- /documentation/MezzanineProducts/UARTSerial/
```

Thanks
Shovan
