### ISSUE TITLE
Broken navlink at the top of every page

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/documentation#97]
Hi @shovanuk 

Out of curiosity I ran a broken link checker across the static documentation...

I think it found a couple of real problems but it is hard to tell because there was so much noise. The noise comes because each generated page contains a broken link to itself as part of the generate navigation links.

For example:

http://www.96boards.org/documentation/ConsumerEdition/Bubblegum-96/GettingStarted/ has a proper nav link but this page contains raw .md links such as http://www.96boards.org/documentation/ConsumerEdition/Bubblegum-96/GettingStarted/PowerAdapter.md and this contains a broken link to (not quite) itself.

This is a such a common pattern that it makes it very hard to interpret the rest of the report. Can these self-links be removed?

Daniel.

**Comment by shovanuk** [comment]
@kylekirkby and I will check and get back

**Comment by shovanuk** [comment]
@kylekirkby check
http://www.96boards.org/documentation/IoTEdition/carbon/installation/

Click on Downloads or Build its broken

**Comment by sdrobertw** [comment]
@shovanuk Downloads and Build links have been fixed on back end: http://www.96boards.org/documentation/IoTEdition/carbon/installation/

**Comment by sdrobertw** [comment]
@shovanuk @kylekirkby has this been fixed? Can we close this issue?

**Comment by shovanuk** [comment]
@kylekirkby @sdrobertw 

1. Board Recovery link is broken
http://www.96boards.org/documentation/ConsumerEdition/Bubblegum-96/GettingStarted/

2. Power Adapter has not been linked from anywhere but the formating is off
http://www.96boards.org/documentation/ConsumerEdition/Bubblegum-96/GettingStarted/PowerAdapter.md

**Comment by kylekirkby** [comment]
Hi all, 

We should be able to close this now - cannot see any broken links in the breadcrumb.

Many Thanks,

Kyle
